<?php
/**
 * ActionType
 *
 * PHP version 8.1
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace \Kehet\ArtifactsMMO\\Model;

/**
 * ActionType Class Doc Comment
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ActionType: string
{
    case MOVEMENT = 'movement';

    case FIGHT = 'fight';

    case MULTI_FIGHT = 'multi_fight';

    case CRAFTING = 'crafting';

    case GATHERING = 'gathering';

    case BUY_GE = 'buy_ge';

    case SELL_GE = 'sell_ge';

    case BUY_NPC = 'buy_npc';

    case SELL_NPC = 'sell_npc';

    case CANCEL_GE = 'cancel_ge';

    case DELETE_ITEM = 'delete_item';

    case DEPOSIT_ITEM = 'deposit_item';

    case WITHDRAW_ITEM = 'withdraw_item';

    case DEPOSIT_GOLD = 'deposit_gold';

    case WITHDRAW_GOLD = 'withdraw_gold';

    case EQUIP = 'equip';

    case UNEQUIP = 'unequip';

    case TASK = 'task';

    case RECYCLING = 'recycling';

    case REST = 'rest';

    case _USE = 'use';

    case BUY_BANK_EXPANSION = 'buy_bank_expansion';

    case GIVE_ITEM = 'give_item';

    case GIVE_GOLD = 'give_gold';

    case CHANGE_SKIN = 'change_skin';

    case RENAME = 'rename';

    case TRANSITION = 'transition';
}


