<?php
/**
 * CharacterSchema
 *
 * PHP version 8.1
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace \Kehet\ArtifactsMMO\\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use \Kehet\ArtifactsMMO\\ObjectSerializer;

/**
 * CharacterSchema Class Doc Comment
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CharacterSchema implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'CharacterSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'name' => 'string',
        'account' => 'string',
        'skin' => '\\Kehet\ArtifactsMMO\\Model\CharacterSkin',
        'level' => 'int',
        'xp' => 'int',
        'max_xp' => 'int',
        'gold' => 'int',
        'speed' => 'int',
        'mining_level' => 'int',
        'mining_xp' => 'int',
        'mining_max_xp' => 'int',
        'woodcutting_level' => 'int',
        'woodcutting_xp' => 'int',
        'woodcutting_max_xp' => 'int',
        'fishing_level' => 'int',
        'fishing_xp' => 'int',
        'fishing_max_xp' => 'int',
        'weaponcrafting_level' => 'int',
        'weaponcrafting_xp' => 'int',
        'weaponcrafting_max_xp' => 'int',
        'gearcrafting_level' => 'int',
        'gearcrafting_xp' => 'int',
        'gearcrafting_max_xp' => 'int',
        'jewelrycrafting_level' => 'int',
        'jewelrycrafting_xp' => 'int',
        'jewelrycrafting_max_xp' => 'int',
        'cooking_level' => 'int',
        'cooking_xp' => 'int',
        'cooking_max_xp' => 'int',
        'alchemy_level' => 'int',
        'alchemy_xp' => 'int',
        'alchemy_max_xp' => 'int',
        'hp' => 'int',
        'max_hp' => 'int',
        'haste' => 'int',
        'critical_strike' => 'int',
        'wisdom' => 'int',
        'prospecting' => 'int',
        'initiative' => 'int',
        'threat' => 'int',
        'attack_fire' => 'int',
        'attack_earth' => 'int',
        'attack_water' => 'int',
        'attack_air' => 'int',
        'dmg' => 'int',
        'dmg_fire' => 'int',
        'dmg_earth' => 'int',
        'dmg_water' => 'int',
        'dmg_air' => 'int',
        'res_fire' => 'int',
        'res_earth' => 'int',
        'res_water' => 'int',
        'res_air' => 'int',
        'effects' => '\\Kehet\ArtifactsMMO\\Model\StorageEffectSchema[]',
        'x' => 'int',
        'y' => 'int',
        'layer' => '\\Kehet\ArtifactsMMO\\Model\MapLayer',
        'map_id' => 'int',
        'cooldown' => 'int',
        'cooldown_expiration' => '\DateTime',
        'weapon_slot' => 'string',
        'rune_slot' => 'string',
        'shield_slot' => 'string',
        'helmet_slot' => 'string',
        'body_armor_slot' => 'string',
        'leg_armor_slot' => 'string',
        'boots_slot' => 'string',
        'ring1_slot' => 'string',
        'ring2_slot' => 'string',
        'amulet_slot' => 'string',
        'artifact1_slot' => 'string',
        'artifact2_slot' => 'string',
        'artifact3_slot' => 'string',
        'utility1_slot' => 'string',
        'utility1_slot_quantity' => 'int',
        'utility2_slot' => 'string',
        'utility2_slot_quantity' => 'int',
        'bag_slot' => 'string',
        'task' => 'string',
        'task_type' => 'string',
        'task_progress' => 'int',
        'task_total' => 'int',
        'inventory_max_items' => 'int',
        'inventory' => '\\Kehet\ArtifactsMMO\\Model\InventorySlot[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'name' => null,
        'account' => null,
        'skin' => null,
        'level' => null,
        'xp' => null,
        'max_xp' => null,
        'gold' => null,
        'speed' => null,
        'mining_level' => null,
        'mining_xp' => null,
        'mining_max_xp' => null,
        'woodcutting_level' => null,
        'woodcutting_xp' => null,
        'woodcutting_max_xp' => null,
        'fishing_level' => null,
        'fishing_xp' => null,
        'fishing_max_xp' => null,
        'weaponcrafting_level' => null,
        'weaponcrafting_xp' => null,
        'weaponcrafting_max_xp' => null,
        'gearcrafting_level' => null,
        'gearcrafting_xp' => null,
        'gearcrafting_max_xp' => null,
        'jewelrycrafting_level' => null,
        'jewelrycrafting_xp' => null,
        'jewelrycrafting_max_xp' => null,
        'cooking_level' => null,
        'cooking_xp' => null,
        'cooking_max_xp' => null,
        'alchemy_level' => null,
        'alchemy_xp' => null,
        'alchemy_max_xp' => null,
        'hp' => null,
        'max_hp' => null,
        'haste' => null,
        'critical_strike' => null,
        'wisdom' => null,
        'prospecting' => null,
        'initiative' => null,
        'threat' => null,
        'attack_fire' => null,
        'attack_earth' => null,
        'attack_water' => null,
        'attack_air' => null,
        'dmg' => null,
        'dmg_fire' => null,
        'dmg_earth' => null,
        'dmg_water' => null,
        'dmg_air' => null,
        'res_fire' => null,
        'res_earth' => null,
        'res_water' => null,
        'res_air' => null,
        'effects' => null,
        'x' => null,
        'y' => null,
        'layer' => null,
        'map_id' => null,
        'cooldown' => null,
        'cooldown_expiration' => 'date-time',
        'weapon_slot' => null,
        'rune_slot' => null,
        'shield_slot' => null,
        'helmet_slot' => null,
        'body_armor_slot' => null,
        'leg_armor_slot' => null,
        'boots_slot' => null,
        'ring1_slot' => null,
        'ring2_slot' => null,
        'amulet_slot' => null,
        'artifact1_slot' => null,
        'artifact2_slot' => null,
        'artifact3_slot' => null,
        'utility1_slot' => null,
        'utility1_slot_quantity' => null,
        'utility2_slot' => null,
        'utility2_slot_quantity' => null,
        'bag_slot' => null,
        'task' => null,
        'task_type' => null,
        'task_progress' => null,
        'task_total' => null,
        'inventory_max_items' => null,
        'inventory' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'name' => false,
        'account' => false,
        'skin' => false,
        'level' => false,
        'xp' => false,
        'max_xp' => false,
        'gold' => false,
        'speed' => false,
        'mining_level' => false,
        'mining_xp' => false,
        'mining_max_xp' => false,
        'woodcutting_level' => false,
        'woodcutting_xp' => false,
        'woodcutting_max_xp' => false,
        'fishing_level' => false,
        'fishing_xp' => false,
        'fishing_max_xp' => false,
        'weaponcrafting_level' => false,
        'weaponcrafting_xp' => false,
        'weaponcrafting_max_xp' => false,
        'gearcrafting_level' => false,
        'gearcrafting_xp' => false,
        'gearcrafting_max_xp' => false,
        'jewelrycrafting_level' => false,
        'jewelrycrafting_xp' => false,
        'jewelrycrafting_max_xp' => false,
        'cooking_level' => false,
        'cooking_xp' => false,
        'cooking_max_xp' => false,
        'alchemy_level' => false,
        'alchemy_xp' => false,
        'alchemy_max_xp' => false,
        'hp' => false,
        'max_hp' => false,
        'haste' => false,
        'critical_strike' => false,
        'wisdom' => false,
        'prospecting' => false,
        'initiative' => false,
        'threat' => false,
        'attack_fire' => false,
        'attack_earth' => false,
        'attack_water' => false,
        'attack_air' => false,
        'dmg' => false,
        'dmg_fire' => false,
        'dmg_earth' => false,
        'dmg_water' => false,
        'dmg_air' => false,
        'res_fire' => false,
        'res_earth' => false,
        'res_water' => false,
        'res_air' => false,
        'effects' => false,
        'x' => false,
        'y' => false,
        'layer' => false,
        'map_id' => false,
        'cooldown' => false,
        'cooldown_expiration' => false,
        'weapon_slot' => false,
        'rune_slot' => false,
        'shield_slot' => false,
        'helmet_slot' => false,
        'body_armor_slot' => false,
        'leg_armor_slot' => false,
        'boots_slot' => false,
        'ring1_slot' => false,
        'ring2_slot' => false,
        'amulet_slot' => false,
        'artifact1_slot' => false,
        'artifact2_slot' => false,
        'artifact3_slot' => false,
        'utility1_slot' => false,
        'utility1_slot_quantity' => false,
        'utility2_slot' => false,
        'utility2_slot_quantity' => false,
        'bag_slot' => false,
        'task' => false,
        'task_type' => false,
        'task_progress' => false,
        'task_total' => false,
        'inventory_max_items' => false,
        'inventory' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'name' => 'name',
        'account' => 'account',
        'skin' => 'skin',
        'level' => 'level',
        'xp' => 'xp',
        'max_xp' => 'max_xp',
        'gold' => 'gold',
        'speed' => 'speed',
        'mining_level' => 'mining_level',
        'mining_xp' => 'mining_xp',
        'mining_max_xp' => 'mining_max_xp',
        'woodcutting_level' => 'woodcutting_level',
        'woodcutting_xp' => 'woodcutting_xp',
        'woodcutting_max_xp' => 'woodcutting_max_xp',
        'fishing_level' => 'fishing_level',
        'fishing_xp' => 'fishing_xp',
        'fishing_max_xp' => 'fishing_max_xp',
        'weaponcrafting_level' => 'weaponcrafting_level',
        'weaponcrafting_xp' => 'weaponcrafting_xp',
        'weaponcrafting_max_xp' => 'weaponcrafting_max_xp',
        'gearcrafting_level' => 'gearcrafting_level',
        'gearcrafting_xp' => 'gearcrafting_xp',
        'gearcrafting_max_xp' => 'gearcrafting_max_xp',
        'jewelrycrafting_level' => 'jewelrycrafting_level',
        'jewelrycrafting_xp' => 'jewelrycrafting_xp',
        'jewelrycrafting_max_xp' => 'jewelrycrafting_max_xp',
        'cooking_level' => 'cooking_level',
        'cooking_xp' => 'cooking_xp',
        'cooking_max_xp' => 'cooking_max_xp',
        'alchemy_level' => 'alchemy_level',
        'alchemy_xp' => 'alchemy_xp',
        'alchemy_max_xp' => 'alchemy_max_xp',
        'hp' => 'hp',
        'max_hp' => 'max_hp',
        'haste' => 'haste',
        'critical_strike' => 'critical_strike',
        'wisdom' => 'wisdom',
        'prospecting' => 'prospecting',
        'initiative' => 'initiative',
        'threat' => 'threat',
        'attack_fire' => 'attack_fire',
        'attack_earth' => 'attack_earth',
        'attack_water' => 'attack_water',
        'attack_air' => 'attack_air',
        'dmg' => 'dmg',
        'dmg_fire' => 'dmg_fire',
        'dmg_earth' => 'dmg_earth',
        'dmg_water' => 'dmg_water',
        'dmg_air' => 'dmg_air',
        'res_fire' => 'res_fire',
        'res_earth' => 'res_earth',
        'res_water' => 'res_water',
        'res_air' => 'res_air',
        'effects' => 'effects',
        'x' => 'x',
        'y' => 'y',
        'layer' => 'layer',
        'map_id' => 'map_id',
        'cooldown' => 'cooldown',
        'cooldown_expiration' => 'cooldown_expiration',
        'weapon_slot' => 'weapon_slot',
        'rune_slot' => 'rune_slot',
        'shield_slot' => 'shield_slot',
        'helmet_slot' => 'helmet_slot',
        'body_armor_slot' => 'body_armor_slot',
        'leg_armor_slot' => 'leg_armor_slot',
        'boots_slot' => 'boots_slot',
        'ring1_slot' => 'ring1_slot',
        'ring2_slot' => 'ring2_slot',
        'amulet_slot' => 'amulet_slot',
        'artifact1_slot' => 'artifact1_slot',
        'artifact2_slot' => 'artifact2_slot',
        'artifact3_slot' => 'artifact3_slot',
        'utility1_slot' => 'utility1_slot',
        'utility1_slot_quantity' => 'utility1_slot_quantity',
        'utility2_slot' => 'utility2_slot',
        'utility2_slot_quantity' => 'utility2_slot_quantity',
        'bag_slot' => 'bag_slot',
        'task' => 'task',
        'task_type' => 'task_type',
        'task_progress' => 'task_progress',
        'task_total' => 'task_total',
        'inventory_max_items' => 'inventory_max_items',
        'inventory' => 'inventory'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'name' => 'setName',
        'account' => 'setAccount',
        'skin' => 'setSkin',
        'level' => 'setLevel',
        'xp' => 'setXp',
        'max_xp' => 'setMaxXp',
        'gold' => 'setGold',
        'speed' => 'setSpeed',
        'mining_level' => 'setMiningLevel',
        'mining_xp' => 'setMiningXp',
        'mining_max_xp' => 'setMiningMaxXp',
        'woodcutting_level' => 'setWoodcuttingLevel',
        'woodcutting_xp' => 'setWoodcuttingXp',
        'woodcutting_max_xp' => 'setWoodcuttingMaxXp',
        'fishing_level' => 'setFishingLevel',
        'fishing_xp' => 'setFishingXp',
        'fishing_max_xp' => 'setFishingMaxXp',
        'weaponcrafting_level' => 'setWeaponcraftingLevel',
        'weaponcrafting_xp' => 'setWeaponcraftingXp',
        'weaponcrafting_max_xp' => 'setWeaponcraftingMaxXp',
        'gearcrafting_level' => 'setGearcraftingLevel',
        'gearcrafting_xp' => 'setGearcraftingXp',
        'gearcrafting_max_xp' => 'setGearcraftingMaxXp',
        'jewelrycrafting_level' => 'setJewelrycraftingLevel',
        'jewelrycrafting_xp' => 'setJewelrycraftingXp',
        'jewelrycrafting_max_xp' => 'setJewelrycraftingMaxXp',
        'cooking_level' => 'setCookingLevel',
        'cooking_xp' => 'setCookingXp',
        'cooking_max_xp' => 'setCookingMaxXp',
        'alchemy_level' => 'setAlchemyLevel',
        'alchemy_xp' => 'setAlchemyXp',
        'alchemy_max_xp' => 'setAlchemyMaxXp',
        'hp' => 'setHp',
        'max_hp' => 'setMaxHp',
        'haste' => 'setHaste',
        'critical_strike' => 'setCriticalStrike',
        'wisdom' => 'setWisdom',
        'prospecting' => 'setProspecting',
        'initiative' => 'setInitiative',
        'threat' => 'setThreat',
        'attack_fire' => 'setAttackFire',
        'attack_earth' => 'setAttackEarth',
        'attack_water' => 'setAttackWater',
        'attack_air' => 'setAttackAir',
        'dmg' => 'setDmg',
        'dmg_fire' => 'setDmgFire',
        'dmg_earth' => 'setDmgEarth',
        'dmg_water' => 'setDmgWater',
        'dmg_air' => 'setDmgAir',
        'res_fire' => 'setResFire',
        'res_earth' => 'setResEarth',
        'res_water' => 'setResWater',
        'res_air' => 'setResAir',
        'effects' => 'setEffects',
        'x' => 'setX',
        'y' => 'setY',
        'layer' => 'setLayer',
        'map_id' => 'setMapId',
        'cooldown' => 'setCooldown',
        'cooldown_expiration' => 'setCooldownExpiration',
        'weapon_slot' => 'setWeaponSlot',
        'rune_slot' => 'setRuneSlot',
        'shield_slot' => 'setShieldSlot',
        'helmet_slot' => 'setHelmetSlot',
        'body_armor_slot' => 'setBodyArmorSlot',
        'leg_armor_slot' => 'setLegArmorSlot',
        'boots_slot' => 'setBootsSlot',
        'ring1_slot' => 'setRing1Slot',
        'ring2_slot' => 'setRing2Slot',
        'amulet_slot' => 'setAmuletSlot',
        'artifact1_slot' => 'setArtifact1Slot',
        'artifact2_slot' => 'setArtifact2Slot',
        'artifact3_slot' => 'setArtifact3Slot',
        'utility1_slot' => 'setUtility1Slot',
        'utility1_slot_quantity' => 'setUtility1SlotQuantity',
        'utility2_slot' => 'setUtility2Slot',
        'utility2_slot_quantity' => 'setUtility2SlotQuantity',
        'bag_slot' => 'setBagSlot',
        'task' => 'setTask',
        'task_type' => 'setTaskType',
        'task_progress' => 'setTaskProgress',
        'task_total' => 'setTaskTotal',
        'inventory_max_items' => 'setInventoryMaxItems',
        'inventory' => 'setInventory'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'name' => 'getName',
        'account' => 'getAccount',
        'skin' => 'getSkin',
        'level' => 'getLevel',
        'xp' => 'getXp',
        'max_xp' => 'getMaxXp',
        'gold' => 'getGold',
        'speed' => 'getSpeed',
        'mining_level' => 'getMiningLevel',
        'mining_xp' => 'getMiningXp',
        'mining_max_xp' => 'getMiningMaxXp',
        'woodcutting_level' => 'getWoodcuttingLevel',
        'woodcutting_xp' => 'getWoodcuttingXp',
        'woodcutting_max_xp' => 'getWoodcuttingMaxXp',
        'fishing_level' => 'getFishingLevel',
        'fishing_xp' => 'getFishingXp',
        'fishing_max_xp' => 'getFishingMaxXp',
        'weaponcrafting_level' => 'getWeaponcraftingLevel',
        'weaponcrafting_xp' => 'getWeaponcraftingXp',
        'weaponcrafting_max_xp' => 'getWeaponcraftingMaxXp',
        'gearcrafting_level' => 'getGearcraftingLevel',
        'gearcrafting_xp' => 'getGearcraftingXp',
        'gearcrafting_max_xp' => 'getGearcraftingMaxXp',
        'jewelrycrafting_level' => 'getJewelrycraftingLevel',
        'jewelrycrafting_xp' => 'getJewelrycraftingXp',
        'jewelrycrafting_max_xp' => 'getJewelrycraftingMaxXp',
        'cooking_level' => 'getCookingLevel',
        'cooking_xp' => 'getCookingXp',
        'cooking_max_xp' => 'getCookingMaxXp',
        'alchemy_level' => 'getAlchemyLevel',
        'alchemy_xp' => 'getAlchemyXp',
        'alchemy_max_xp' => 'getAlchemyMaxXp',
        'hp' => 'getHp',
        'max_hp' => 'getMaxHp',
        'haste' => 'getHaste',
        'critical_strike' => 'getCriticalStrike',
        'wisdom' => 'getWisdom',
        'prospecting' => 'getProspecting',
        'initiative' => 'getInitiative',
        'threat' => 'getThreat',
        'attack_fire' => 'getAttackFire',
        'attack_earth' => 'getAttackEarth',
        'attack_water' => 'getAttackWater',
        'attack_air' => 'getAttackAir',
        'dmg' => 'getDmg',
        'dmg_fire' => 'getDmgFire',
        'dmg_earth' => 'getDmgEarth',
        'dmg_water' => 'getDmgWater',
        'dmg_air' => 'getDmgAir',
        'res_fire' => 'getResFire',
        'res_earth' => 'getResEarth',
        'res_water' => 'getResWater',
        'res_air' => 'getResAir',
        'effects' => 'getEffects',
        'x' => 'getX',
        'y' => 'getY',
        'layer' => 'getLayer',
        'map_id' => 'getMapId',
        'cooldown' => 'getCooldown',
        'cooldown_expiration' => 'getCooldownExpiration',
        'weapon_slot' => 'getWeaponSlot',
        'rune_slot' => 'getRuneSlot',
        'shield_slot' => 'getShieldSlot',
        'helmet_slot' => 'getHelmetSlot',
        'body_armor_slot' => 'getBodyArmorSlot',
        'leg_armor_slot' => 'getLegArmorSlot',
        'boots_slot' => 'getBootsSlot',
        'ring1_slot' => 'getRing1Slot',
        'ring2_slot' => 'getRing2Slot',
        'amulet_slot' => 'getAmuletSlot',
        'artifact1_slot' => 'getArtifact1Slot',
        'artifact2_slot' => 'getArtifact2Slot',
        'artifact3_slot' => 'getArtifact3Slot',
        'utility1_slot' => 'getUtility1Slot',
        'utility1_slot_quantity' => 'getUtility1SlotQuantity',
        'utility2_slot' => 'getUtility2Slot',
        'utility2_slot_quantity' => 'getUtility2SlotQuantity',
        'bag_slot' => 'getBagSlot',
        'task' => 'getTask',
        'task_type' => 'getTaskType',
        'task_progress' => 'getTaskProgress',
        'task_total' => 'getTaskTotal',
        'inventory_max_items' => 'getInventoryMaxItems',
        'inventory' => 'getInventory'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('account', $data ?? [], null);
        $this->setIfExists('skin', $data ?? [], null);
        $this->setIfExists('level', $data ?? [], null);
        $this->setIfExists('xp', $data ?? [], null);
        $this->setIfExists('max_xp', $data ?? [], null);
        $this->setIfExists('gold', $data ?? [], null);
        $this->setIfExists('speed', $data ?? [], null);
        $this->setIfExists('mining_level', $data ?? [], null);
        $this->setIfExists('mining_xp', $data ?? [], null);
        $this->setIfExists('mining_max_xp', $data ?? [], null);
        $this->setIfExists('woodcutting_level', $data ?? [], null);
        $this->setIfExists('woodcutting_xp', $data ?? [], null);
        $this->setIfExists('woodcutting_max_xp', $data ?? [], null);
        $this->setIfExists('fishing_level', $data ?? [], null);
        $this->setIfExists('fishing_xp', $data ?? [], null);
        $this->setIfExists('fishing_max_xp', $data ?? [], null);
        $this->setIfExists('weaponcrafting_level', $data ?? [], null);
        $this->setIfExists('weaponcrafting_xp', $data ?? [], null);
        $this->setIfExists('weaponcrafting_max_xp', $data ?? [], null);
        $this->setIfExists('gearcrafting_level', $data ?? [], null);
        $this->setIfExists('gearcrafting_xp', $data ?? [], null);
        $this->setIfExists('gearcrafting_max_xp', $data ?? [], null);
        $this->setIfExists('jewelrycrafting_level', $data ?? [], null);
        $this->setIfExists('jewelrycrafting_xp', $data ?? [], null);
        $this->setIfExists('jewelrycrafting_max_xp', $data ?? [], null);
        $this->setIfExists('cooking_level', $data ?? [], null);
        $this->setIfExists('cooking_xp', $data ?? [], null);
        $this->setIfExists('cooking_max_xp', $data ?? [], null);
        $this->setIfExists('alchemy_level', $data ?? [], null);
        $this->setIfExists('alchemy_xp', $data ?? [], null);
        $this->setIfExists('alchemy_max_xp', $data ?? [], null);
        $this->setIfExists('hp', $data ?? [], null);
        $this->setIfExists('max_hp', $data ?? [], null);
        $this->setIfExists('haste', $data ?? [], null);
        $this->setIfExists('critical_strike', $data ?? [], null);
        $this->setIfExists('wisdom', $data ?? [], null);
        $this->setIfExists('prospecting', $data ?? [], null);
        $this->setIfExists('initiative', $data ?? [], null);
        $this->setIfExists('threat', $data ?? [], null);
        $this->setIfExists('attack_fire', $data ?? [], null);
        $this->setIfExists('attack_earth', $data ?? [], null);
        $this->setIfExists('attack_water', $data ?? [], null);
        $this->setIfExists('attack_air', $data ?? [], null);
        $this->setIfExists('dmg', $data ?? [], null);
        $this->setIfExists('dmg_fire', $data ?? [], null);
        $this->setIfExists('dmg_earth', $data ?? [], null);
        $this->setIfExists('dmg_water', $data ?? [], null);
        $this->setIfExists('dmg_air', $data ?? [], null);
        $this->setIfExists('res_fire', $data ?? [], null);
        $this->setIfExists('res_earth', $data ?? [], null);
        $this->setIfExists('res_water', $data ?? [], null);
        $this->setIfExists('res_air', $data ?? [], null);
        $this->setIfExists('effects', $data ?? [], null);
        $this->setIfExists('x', $data ?? [], null);
        $this->setIfExists('y', $data ?? [], null);
        $this->setIfExists('layer', $data ?? [], null);
        $this->setIfExists('map_id', $data ?? [], null);
        $this->setIfExists('cooldown', $data ?? [], null);
        $this->setIfExists('cooldown_expiration', $data ?? [], null);
        $this->setIfExists('weapon_slot', $data ?? [], null);
        $this->setIfExists('rune_slot', $data ?? [], null);
        $this->setIfExists('shield_slot', $data ?? [], null);
        $this->setIfExists('helmet_slot', $data ?? [], null);
        $this->setIfExists('body_armor_slot', $data ?? [], null);
        $this->setIfExists('leg_armor_slot', $data ?? [], null);
        $this->setIfExists('boots_slot', $data ?? [], null);
        $this->setIfExists('ring1_slot', $data ?? [], null);
        $this->setIfExists('ring2_slot', $data ?? [], null);
        $this->setIfExists('amulet_slot', $data ?? [], null);
        $this->setIfExists('artifact1_slot', $data ?? [], null);
        $this->setIfExists('artifact2_slot', $data ?? [], null);
        $this->setIfExists('artifact3_slot', $data ?? [], null);
        $this->setIfExists('utility1_slot', $data ?? [], null);
        $this->setIfExists('utility1_slot_quantity', $data ?? [], null);
        $this->setIfExists('utility2_slot', $data ?? [], null);
        $this->setIfExists('utility2_slot_quantity', $data ?? [], null);
        $this->setIfExists('bag_slot', $data ?? [], null);
        $this->setIfExists('task', $data ?? [], null);
        $this->setIfExists('task_type', $data ?? [], null);
        $this->setIfExists('task_progress', $data ?? [], null);
        $this->setIfExists('task_total', $data ?? [], null);
        $this->setIfExists('inventory_max_items', $data ?? [], null);
        $this->setIfExists('inventory', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['account'] === null) {
            $invalidProperties[] = "'account' can't be null";
        }
        if ($this->container['skin'] === null) {
            $invalidProperties[] = "'skin' can't be null";
        }
        if ($this->container['level'] === null) {
            $invalidProperties[] = "'level' can't be null";
        }
        if ($this->container['xp'] === null) {
            $invalidProperties[] = "'xp' can't be null";
        }
        if ($this->container['max_xp'] === null) {
            $invalidProperties[] = "'max_xp' can't be null";
        }
        if ($this->container['gold'] === null) {
            $invalidProperties[] = "'gold' can't be null";
        }
        if ($this->container['speed'] === null) {
            $invalidProperties[] = "'speed' can't be null";
        }
        if ($this->container['mining_level'] === null) {
            $invalidProperties[] = "'mining_level' can't be null";
        }
        if ($this->container['mining_xp'] === null) {
            $invalidProperties[] = "'mining_xp' can't be null";
        }
        if ($this->container['mining_max_xp'] === null) {
            $invalidProperties[] = "'mining_max_xp' can't be null";
        }
        if ($this->container['woodcutting_level'] === null) {
            $invalidProperties[] = "'woodcutting_level' can't be null";
        }
        if ($this->container['woodcutting_xp'] === null) {
            $invalidProperties[] = "'woodcutting_xp' can't be null";
        }
        if ($this->container['woodcutting_max_xp'] === null) {
            $invalidProperties[] = "'woodcutting_max_xp' can't be null";
        }
        if ($this->container['fishing_level'] === null) {
            $invalidProperties[] = "'fishing_level' can't be null";
        }
        if ($this->container['fishing_xp'] === null) {
            $invalidProperties[] = "'fishing_xp' can't be null";
        }
        if ($this->container['fishing_max_xp'] === null) {
            $invalidProperties[] = "'fishing_max_xp' can't be null";
        }
        if ($this->container['weaponcrafting_level'] === null) {
            $invalidProperties[] = "'weaponcrafting_level' can't be null";
        }
        if ($this->container['weaponcrafting_xp'] === null) {
            $invalidProperties[] = "'weaponcrafting_xp' can't be null";
        }
        if ($this->container['weaponcrafting_max_xp'] === null) {
            $invalidProperties[] = "'weaponcrafting_max_xp' can't be null";
        }
        if ($this->container['gearcrafting_level'] === null) {
            $invalidProperties[] = "'gearcrafting_level' can't be null";
        }
        if ($this->container['gearcrafting_xp'] === null) {
            $invalidProperties[] = "'gearcrafting_xp' can't be null";
        }
        if ($this->container['gearcrafting_max_xp'] === null) {
            $invalidProperties[] = "'gearcrafting_max_xp' can't be null";
        }
        if ($this->container['jewelrycrafting_level'] === null) {
            $invalidProperties[] = "'jewelrycrafting_level' can't be null";
        }
        if ($this->container['jewelrycrafting_xp'] === null) {
            $invalidProperties[] = "'jewelrycrafting_xp' can't be null";
        }
        if ($this->container['jewelrycrafting_max_xp'] === null) {
            $invalidProperties[] = "'jewelrycrafting_max_xp' can't be null";
        }
        if ($this->container['cooking_level'] === null) {
            $invalidProperties[] = "'cooking_level' can't be null";
        }
        if ($this->container['cooking_xp'] === null) {
            $invalidProperties[] = "'cooking_xp' can't be null";
        }
        if ($this->container['cooking_max_xp'] === null) {
            $invalidProperties[] = "'cooking_max_xp' can't be null";
        }
        if ($this->container['alchemy_level'] === null) {
            $invalidProperties[] = "'alchemy_level' can't be null";
        }
        if ($this->container['alchemy_xp'] === null) {
            $invalidProperties[] = "'alchemy_xp' can't be null";
        }
        if ($this->container['alchemy_max_xp'] === null) {
            $invalidProperties[] = "'alchemy_max_xp' can't be null";
        }
        if ($this->container['hp'] === null) {
            $invalidProperties[] = "'hp' can't be null";
        }
        if ($this->container['max_hp'] === null) {
            $invalidProperties[] = "'max_hp' can't be null";
        }
        if ($this->container['haste'] === null) {
            $invalidProperties[] = "'haste' can't be null";
        }
        if ($this->container['critical_strike'] === null) {
            $invalidProperties[] = "'critical_strike' can't be null";
        }
        if ($this->container['wisdom'] === null) {
            $invalidProperties[] = "'wisdom' can't be null";
        }
        if ($this->container['prospecting'] === null) {
            $invalidProperties[] = "'prospecting' can't be null";
        }
        if ($this->container['initiative'] === null) {
            $invalidProperties[] = "'initiative' can't be null";
        }
        if ($this->container['threat'] === null) {
            $invalidProperties[] = "'threat' can't be null";
        }
        if ($this->container['attack_fire'] === null) {
            $invalidProperties[] = "'attack_fire' can't be null";
        }
        if ($this->container['attack_earth'] === null) {
            $invalidProperties[] = "'attack_earth' can't be null";
        }
        if ($this->container['attack_water'] === null) {
            $invalidProperties[] = "'attack_water' can't be null";
        }
        if ($this->container['attack_air'] === null) {
            $invalidProperties[] = "'attack_air' can't be null";
        }
        if ($this->container['dmg'] === null) {
            $invalidProperties[] = "'dmg' can't be null";
        }
        if ($this->container['dmg_fire'] === null) {
            $invalidProperties[] = "'dmg_fire' can't be null";
        }
        if ($this->container['dmg_earth'] === null) {
            $invalidProperties[] = "'dmg_earth' can't be null";
        }
        if ($this->container['dmg_water'] === null) {
            $invalidProperties[] = "'dmg_water' can't be null";
        }
        if ($this->container['dmg_air'] === null) {
            $invalidProperties[] = "'dmg_air' can't be null";
        }
        if ($this->container['res_fire'] === null) {
            $invalidProperties[] = "'res_fire' can't be null";
        }
        if ($this->container['res_earth'] === null) {
            $invalidProperties[] = "'res_earth' can't be null";
        }
        if ($this->container['res_water'] === null) {
            $invalidProperties[] = "'res_water' can't be null";
        }
        if ($this->container['res_air'] === null) {
            $invalidProperties[] = "'res_air' can't be null";
        }
        if ($this->container['x'] === null) {
            $invalidProperties[] = "'x' can't be null";
        }
        if ($this->container['y'] === null) {
            $invalidProperties[] = "'y' can't be null";
        }
        if ($this->container['layer'] === null) {
            $invalidProperties[] = "'layer' can't be null";
        }
        if ($this->container['map_id'] === null) {
            $invalidProperties[] = "'map_id' can't be null";
        }
        if ($this->container['cooldown'] === null) {
            $invalidProperties[] = "'cooldown' can't be null";
        }
        if ($this->container['weapon_slot'] === null) {
            $invalidProperties[] = "'weapon_slot' can't be null";
        }
        if ($this->container['rune_slot'] === null) {
            $invalidProperties[] = "'rune_slot' can't be null";
        }
        if ($this->container['shield_slot'] === null) {
            $invalidProperties[] = "'shield_slot' can't be null";
        }
        if ($this->container['helmet_slot'] === null) {
            $invalidProperties[] = "'helmet_slot' can't be null";
        }
        if ($this->container['body_armor_slot'] === null) {
            $invalidProperties[] = "'body_armor_slot' can't be null";
        }
        if ($this->container['leg_armor_slot'] === null) {
            $invalidProperties[] = "'leg_armor_slot' can't be null";
        }
        if ($this->container['boots_slot'] === null) {
            $invalidProperties[] = "'boots_slot' can't be null";
        }
        if ($this->container['ring1_slot'] === null) {
            $invalidProperties[] = "'ring1_slot' can't be null";
        }
        if ($this->container['ring2_slot'] === null) {
            $invalidProperties[] = "'ring2_slot' can't be null";
        }
        if ($this->container['amulet_slot'] === null) {
            $invalidProperties[] = "'amulet_slot' can't be null";
        }
        if ($this->container['artifact1_slot'] === null) {
            $invalidProperties[] = "'artifact1_slot' can't be null";
        }
        if ($this->container['artifact2_slot'] === null) {
            $invalidProperties[] = "'artifact2_slot' can't be null";
        }
        if ($this->container['artifact3_slot'] === null) {
            $invalidProperties[] = "'artifact3_slot' can't be null";
        }
        if ($this->container['utility1_slot'] === null) {
            $invalidProperties[] = "'utility1_slot' can't be null";
        }
        if ($this->container['utility1_slot_quantity'] === null) {
            $invalidProperties[] = "'utility1_slot_quantity' can't be null";
        }
        if (($this->container['utility1_slot_quantity'] < 0)) {
            $invalidProperties[] = "invalid value for 'utility1_slot_quantity', must be bigger than or equal to 0.";
        }

        if ($this->container['utility2_slot'] === null) {
            $invalidProperties[] = "'utility2_slot' can't be null";
        }
        if ($this->container['utility2_slot_quantity'] === null) {
            $invalidProperties[] = "'utility2_slot_quantity' can't be null";
        }
        if (($this->container['utility2_slot_quantity'] < 0)) {
            $invalidProperties[] = "invalid value for 'utility2_slot_quantity', must be bigger than or equal to 0.";
        }

        if ($this->container['bag_slot'] === null) {
            $invalidProperties[] = "'bag_slot' can't be null";
        }
        if ($this->container['task'] === null) {
            $invalidProperties[] = "'task' can't be null";
        }
        if ($this->container['task_type'] === null) {
            $invalidProperties[] = "'task_type' can't be null";
        }
        if ($this->container['task_progress'] === null) {
            $invalidProperties[] = "'task_progress' can't be null";
        }
        if ($this->container['task_total'] === null) {
            $invalidProperties[] = "'task_total' can't be null";
        }
        if ($this->container['inventory_max_items'] === null) {
            $invalidProperties[] = "'inventory_max_items' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name of the character.
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets account
     *
     * @return string
     */
    public function getAccount(): string
    {
        return $this->container['account'];
    }

    /**
     * Sets account
     *
     * @param string $account Account name.
     *
     * @return $this
     */
    public function setAccount(string $account): static
    {
        if (is_null($account)) {
            throw new InvalidArgumentException('non-nullable account cannot be null');
        }
        $this->container['account'] = $account;

        return $this;
    }

    /**
     * Gets skin
     *
     * @return \\Kehet\ArtifactsMMO\\Model\CharacterSkin
     */
    public function getSkin(): \\Kehet\ArtifactsMMO\\Model\CharacterSkin
    {
        return $this->container['skin'];
    }

    /**
     * Sets skin
     *
     * @param \\Kehet\ArtifactsMMO\\Model\CharacterSkin $skin Character skin code.
     *
     * @return $this
     */
    public function setSkin(\\Kehet\ArtifactsMMO\\Model\CharacterSkin $skin): static
    {
        if (is_null($skin)) {
            throw new InvalidArgumentException('non-nullable skin cannot be null');
        }
        $this->container['skin'] = $skin;

        return $this;
    }

    /**
     * Gets level
     *
     * @return int
     */
    public function getLevel(): int
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param int $level Combat level.
     *
     * @return $this
     */
    public function setLevel(int $level): static
    {
        if (is_null($level)) {
            throw new InvalidArgumentException('non-nullable level cannot be null');
        }
        $this->container['level'] = $level;

        return $this;
    }

    /**
     * Gets xp
     *
     * @return int
     */
    public function getXp(): int
    {
        return $this->container['xp'];
    }

    /**
     * Sets xp
     *
     * @param int $xp The current xp level of the combat level.
     *
     * @return $this
     */
    public function setXp(int $xp): static
    {
        if (is_null($xp)) {
            throw new InvalidArgumentException('non-nullable xp cannot be null');
        }
        $this->container['xp'] = $xp;

        return $this;
    }

    /**
     * Gets max_xp
     *
     * @return int
     */
    public function getMaxXp(): int
    {
        return $this->container['max_xp'];
    }

    /**
     * Sets max_xp
     *
     * @param int $max_xp XP required to level up the character.
     *
     * @return $this
     */
    public function setMaxXp(int $max_xp): static
    {
        if (is_null($max_xp)) {
            throw new InvalidArgumentException('non-nullable max_xp cannot be null');
        }
        $this->container['max_xp'] = $max_xp;

        return $this;
    }

    /**
     * Gets gold
     *
     * @return int
     */
    public function getGold(): int
    {
        return $this->container['gold'];
    }

    /**
     * Sets gold
     *
     * @param int $gold The numbers of gold on this character.
     *
     * @return $this
     */
    public function setGold(int $gold): static
    {
        if (is_null($gold)) {
            throw new InvalidArgumentException('non-nullable gold cannot be null');
        }
        $this->container['gold'] = $gold;

        return $this;
    }

    /**
     * Gets speed
     *
     * @return int
     */
    public function getSpeed(): int
    {
        return $this->container['speed'];
    }

    /**
     * Sets speed
     *
     * @param int $speed *Not available, on the roadmap. Character movement speed.
     *
     * @return $this
     */
    public function setSpeed(int $speed): static
    {
        if (is_null($speed)) {
            throw new InvalidArgumentException('non-nullable speed cannot be null');
        }
        $this->container['speed'] = $speed;

        return $this;
    }

    /**
     * Gets mining_level
     *
     * @return int
     */
    public function getMiningLevel(): int
    {
        return $this->container['mining_level'];
    }

    /**
     * Sets mining_level
     *
     * @param int $mining_level Mining level.
     *
     * @return $this
     */
    public function setMiningLevel(int $mining_level): static
    {
        if (is_null($mining_level)) {
            throw new InvalidArgumentException('non-nullable mining_level cannot be null');
        }
        $this->container['mining_level'] = $mining_level;

        return $this;
    }

    /**
     * Gets mining_xp
     *
     * @return int
     */
    public function getMiningXp(): int
    {
        return $this->container['mining_xp'];
    }

    /**
     * Sets mining_xp
     *
     * @param int $mining_xp The current xp level of the Mining skill.
     *
     * @return $this
     */
    public function setMiningXp(int $mining_xp): static
    {
        if (is_null($mining_xp)) {
            throw new InvalidArgumentException('non-nullable mining_xp cannot be null');
        }
        $this->container['mining_xp'] = $mining_xp;

        return $this;
    }

    /**
     * Gets mining_max_xp
     *
     * @return int
     */
    public function getMiningMaxXp(): int
    {
        return $this->container['mining_max_xp'];
    }

    /**
     * Sets mining_max_xp
     *
     * @param int $mining_max_xp Mining XP required to level up the skill.
     *
     * @return $this
     */
    public function setMiningMaxXp(int $mining_max_xp): static
    {
        if (is_null($mining_max_xp)) {
            throw new InvalidArgumentException('non-nullable mining_max_xp cannot be null');
        }
        $this->container['mining_max_xp'] = $mining_max_xp;

        return $this;
    }

    /**
     * Gets woodcutting_level
     *
     * @return int
     */
    public function getWoodcuttingLevel(): int
    {
        return $this->container['woodcutting_level'];
    }

    /**
     * Sets woodcutting_level
     *
     * @param int $woodcutting_level Woodcutting level.
     *
     * @return $this
     */
    public function setWoodcuttingLevel(int $woodcutting_level): static
    {
        if (is_null($woodcutting_level)) {
            throw new InvalidArgumentException('non-nullable woodcutting_level cannot be null');
        }
        $this->container['woodcutting_level'] = $woodcutting_level;

        return $this;
    }

    /**
     * Gets woodcutting_xp
     *
     * @return int
     */
    public function getWoodcuttingXp(): int
    {
        return $this->container['woodcutting_xp'];
    }

    /**
     * Sets woodcutting_xp
     *
     * @param int $woodcutting_xp The current xp level of the Woodcutting skill.
     *
     * @return $this
     */
    public function setWoodcuttingXp(int $woodcutting_xp): static
    {
        if (is_null($woodcutting_xp)) {
            throw new InvalidArgumentException('non-nullable woodcutting_xp cannot be null');
        }
        $this->container['woodcutting_xp'] = $woodcutting_xp;

        return $this;
    }

    /**
     * Gets woodcutting_max_xp
     *
     * @return int
     */
    public function getWoodcuttingMaxXp(): int
    {
        return $this->container['woodcutting_max_xp'];
    }

    /**
     * Sets woodcutting_max_xp
     *
     * @param int $woodcutting_max_xp Woodcutting XP required to level up the skill.
     *
     * @return $this
     */
    public function setWoodcuttingMaxXp(int $woodcutting_max_xp): static
    {
        if (is_null($woodcutting_max_xp)) {
            throw new InvalidArgumentException('non-nullable woodcutting_max_xp cannot be null');
        }
        $this->container['woodcutting_max_xp'] = $woodcutting_max_xp;

        return $this;
    }

    /**
     * Gets fishing_level
     *
     * @return int
     */
    public function getFishingLevel(): int
    {
        return $this->container['fishing_level'];
    }

    /**
     * Sets fishing_level
     *
     * @param int $fishing_level Fishing level.
     *
     * @return $this
     */
    public function setFishingLevel(int $fishing_level): static
    {
        if (is_null($fishing_level)) {
            throw new InvalidArgumentException('non-nullable fishing_level cannot be null');
        }
        $this->container['fishing_level'] = $fishing_level;

        return $this;
    }

    /**
     * Gets fishing_xp
     *
     * @return int
     */
    public function getFishingXp(): int
    {
        return $this->container['fishing_xp'];
    }

    /**
     * Sets fishing_xp
     *
     * @param int $fishing_xp The current xp level of the Fishing skill.
     *
     * @return $this
     */
    public function setFishingXp(int $fishing_xp): static
    {
        if (is_null($fishing_xp)) {
            throw new InvalidArgumentException('non-nullable fishing_xp cannot be null');
        }
        $this->container['fishing_xp'] = $fishing_xp;

        return $this;
    }

    /**
     * Gets fishing_max_xp
     *
     * @return int
     */
    public function getFishingMaxXp(): int
    {
        return $this->container['fishing_max_xp'];
    }

    /**
     * Sets fishing_max_xp
     *
     * @param int $fishing_max_xp Fishing XP required to level up the skill.
     *
     * @return $this
     */
    public function setFishingMaxXp(int $fishing_max_xp): static
    {
        if (is_null($fishing_max_xp)) {
            throw new InvalidArgumentException('non-nullable fishing_max_xp cannot be null');
        }
        $this->container['fishing_max_xp'] = $fishing_max_xp;

        return $this;
    }

    /**
     * Gets weaponcrafting_level
     *
     * @return int
     */
    public function getWeaponcraftingLevel(): int
    {
        return $this->container['weaponcrafting_level'];
    }

    /**
     * Sets weaponcrafting_level
     *
     * @param int $weaponcrafting_level Weaponcrafting level.
     *
     * @return $this
     */
    public function setWeaponcraftingLevel(int $weaponcrafting_level): static
    {
        if (is_null($weaponcrafting_level)) {
            throw new InvalidArgumentException('non-nullable weaponcrafting_level cannot be null');
        }
        $this->container['weaponcrafting_level'] = $weaponcrafting_level;

        return $this;
    }

    /**
     * Gets weaponcrafting_xp
     *
     * @return int
     */
    public function getWeaponcraftingXp(): int
    {
        return $this->container['weaponcrafting_xp'];
    }

    /**
     * Sets weaponcrafting_xp
     *
     * @param int $weaponcrafting_xp The current xp level of the Weaponcrafting skill.
     *
     * @return $this
     */
    public function setWeaponcraftingXp(int $weaponcrafting_xp): static
    {
        if (is_null($weaponcrafting_xp)) {
            throw new InvalidArgumentException('non-nullable weaponcrafting_xp cannot be null');
        }
        $this->container['weaponcrafting_xp'] = $weaponcrafting_xp;

        return $this;
    }

    /**
     * Gets weaponcrafting_max_xp
     *
     * @return int
     */
    public function getWeaponcraftingMaxXp(): int
    {
        return $this->container['weaponcrafting_max_xp'];
    }

    /**
     * Sets weaponcrafting_max_xp
     *
     * @param int $weaponcrafting_max_xp Weaponcrafting XP required to level up the skill.
     *
     * @return $this
     */
    public function setWeaponcraftingMaxXp(int $weaponcrafting_max_xp): static
    {
        if (is_null($weaponcrafting_max_xp)) {
            throw new InvalidArgumentException('non-nullable weaponcrafting_max_xp cannot be null');
        }
        $this->container['weaponcrafting_max_xp'] = $weaponcrafting_max_xp;

        return $this;
    }

    /**
     * Gets gearcrafting_level
     *
     * @return int
     */
    public function getGearcraftingLevel(): int
    {
        return $this->container['gearcrafting_level'];
    }

    /**
     * Sets gearcrafting_level
     *
     * @param int $gearcrafting_level Gearcrafting level.
     *
     * @return $this
     */
    public function setGearcraftingLevel(int $gearcrafting_level): static
    {
        if (is_null($gearcrafting_level)) {
            throw new InvalidArgumentException('non-nullable gearcrafting_level cannot be null');
        }
        $this->container['gearcrafting_level'] = $gearcrafting_level;

        return $this;
    }

    /**
     * Gets gearcrafting_xp
     *
     * @return int
     */
    public function getGearcraftingXp(): int
    {
        return $this->container['gearcrafting_xp'];
    }

    /**
     * Sets gearcrafting_xp
     *
     * @param int $gearcrafting_xp The current xp level of the Gearcrafting skill.
     *
     * @return $this
     */
    public function setGearcraftingXp(int $gearcrafting_xp): static
    {
        if (is_null($gearcrafting_xp)) {
            throw new InvalidArgumentException('non-nullable gearcrafting_xp cannot be null');
        }
        $this->container['gearcrafting_xp'] = $gearcrafting_xp;

        return $this;
    }

    /**
     * Gets gearcrafting_max_xp
     *
     * @return int
     */
    public function getGearcraftingMaxXp(): int
    {
        return $this->container['gearcrafting_max_xp'];
    }

    /**
     * Sets gearcrafting_max_xp
     *
     * @param int $gearcrafting_max_xp Gearcrafting XP required to level up the skill.
     *
     * @return $this
     */
    public function setGearcraftingMaxXp(int $gearcrafting_max_xp): static
    {
        if (is_null($gearcrafting_max_xp)) {
            throw new InvalidArgumentException('non-nullable gearcrafting_max_xp cannot be null');
        }
        $this->container['gearcrafting_max_xp'] = $gearcrafting_max_xp;

        return $this;
    }

    /**
     * Gets jewelrycrafting_level
     *
     * @return int
     */
    public function getJewelrycraftingLevel(): int
    {
        return $this->container['jewelrycrafting_level'];
    }

    /**
     * Sets jewelrycrafting_level
     *
     * @param int $jewelrycrafting_level Jewelrycrafting level.
     *
     * @return $this
     */
    public function setJewelrycraftingLevel(int $jewelrycrafting_level): static
    {
        if (is_null($jewelrycrafting_level)) {
            throw new InvalidArgumentException('non-nullable jewelrycrafting_level cannot be null');
        }
        $this->container['jewelrycrafting_level'] = $jewelrycrafting_level;

        return $this;
    }

    /**
     * Gets jewelrycrafting_xp
     *
     * @return int
     */
    public function getJewelrycraftingXp(): int
    {
        return $this->container['jewelrycrafting_xp'];
    }

    /**
     * Sets jewelrycrafting_xp
     *
     * @param int $jewelrycrafting_xp The current xp level of the Jewelrycrafting skill.
     *
     * @return $this
     */
    public function setJewelrycraftingXp(int $jewelrycrafting_xp): static
    {
        if (is_null($jewelrycrafting_xp)) {
            throw new InvalidArgumentException('non-nullable jewelrycrafting_xp cannot be null');
        }
        $this->container['jewelrycrafting_xp'] = $jewelrycrafting_xp;

        return $this;
    }

    /**
     * Gets jewelrycrafting_max_xp
     *
     * @return int
     */
    public function getJewelrycraftingMaxXp(): int
    {
        return $this->container['jewelrycrafting_max_xp'];
    }

    /**
     * Sets jewelrycrafting_max_xp
     *
     * @param int $jewelrycrafting_max_xp Jewelrycrafting XP required to level up the skill.
     *
     * @return $this
     */
    public function setJewelrycraftingMaxXp(int $jewelrycrafting_max_xp): static
    {
        if (is_null($jewelrycrafting_max_xp)) {
            throw new InvalidArgumentException('non-nullable jewelrycrafting_max_xp cannot be null');
        }
        $this->container['jewelrycrafting_max_xp'] = $jewelrycrafting_max_xp;

        return $this;
    }

    /**
     * Gets cooking_level
     *
     * @return int
     */
    public function getCookingLevel(): int
    {
        return $this->container['cooking_level'];
    }

    /**
     * Sets cooking_level
     *
     * @param int $cooking_level The current xp level of the Cooking skill.
     *
     * @return $this
     */
    public function setCookingLevel(int $cooking_level): static
    {
        if (is_null($cooking_level)) {
            throw new InvalidArgumentException('non-nullable cooking_level cannot be null');
        }
        $this->container['cooking_level'] = $cooking_level;

        return $this;
    }

    /**
     * Gets cooking_xp
     *
     * @return int
     */
    public function getCookingXp(): int
    {
        return $this->container['cooking_xp'];
    }

    /**
     * Sets cooking_xp
     *
     * @param int $cooking_xp Cooking XP.
     *
     * @return $this
     */
    public function setCookingXp(int $cooking_xp): static
    {
        if (is_null($cooking_xp)) {
            throw new InvalidArgumentException('non-nullable cooking_xp cannot be null');
        }
        $this->container['cooking_xp'] = $cooking_xp;

        return $this;
    }

    /**
     * Gets cooking_max_xp
     *
     * @return int
     */
    public function getCookingMaxXp(): int
    {
        return $this->container['cooking_max_xp'];
    }

    /**
     * Sets cooking_max_xp
     *
     * @param int $cooking_max_xp Cooking XP required to level up the skill.
     *
     * @return $this
     */
    public function setCookingMaxXp(int $cooking_max_xp): static
    {
        if (is_null($cooking_max_xp)) {
            throw new InvalidArgumentException('non-nullable cooking_max_xp cannot be null');
        }
        $this->container['cooking_max_xp'] = $cooking_max_xp;

        return $this;
    }

    /**
     * Gets alchemy_level
     *
     * @return int
     */
    public function getAlchemyLevel(): int
    {
        return $this->container['alchemy_level'];
    }

    /**
     * Sets alchemy_level
     *
     * @param int $alchemy_level Alchemy level.
     *
     * @return $this
     */
    public function setAlchemyLevel(int $alchemy_level): static
    {
        if (is_null($alchemy_level)) {
            throw new InvalidArgumentException('non-nullable alchemy_level cannot be null');
        }
        $this->container['alchemy_level'] = $alchemy_level;

        return $this;
    }

    /**
     * Gets alchemy_xp
     *
     * @return int
     */
    public function getAlchemyXp(): int
    {
        return $this->container['alchemy_xp'];
    }

    /**
     * Sets alchemy_xp
     *
     * @param int $alchemy_xp Alchemy XP.
     *
     * @return $this
     */
    public function setAlchemyXp(int $alchemy_xp): static
    {
        if (is_null($alchemy_xp)) {
            throw new InvalidArgumentException('non-nullable alchemy_xp cannot be null');
        }
        $this->container['alchemy_xp'] = $alchemy_xp;

        return $this;
    }

    /**
     * Gets alchemy_max_xp
     *
     * @return int
     */
    public function getAlchemyMaxXp(): int
    {
        return $this->container['alchemy_max_xp'];
    }

    /**
     * Sets alchemy_max_xp
     *
     * @param int $alchemy_max_xp Alchemy XP required to level up the skill.
     *
     * @return $this
     */
    public function setAlchemyMaxXp(int $alchemy_max_xp): static
    {
        if (is_null($alchemy_max_xp)) {
            throw new InvalidArgumentException('non-nullable alchemy_max_xp cannot be null');
        }
        $this->container['alchemy_max_xp'] = $alchemy_max_xp;

        return $this;
    }

    /**
     * Gets hp
     *
     * @return int
     */
    public function getHp(): int
    {
        return $this->container['hp'];
    }

    /**
     * Sets hp
     *
     * @param int $hp Character actual HP.
     *
     * @return $this
     */
    public function setHp(int $hp): static
    {
        if (is_null($hp)) {
            throw new InvalidArgumentException('non-nullable hp cannot be null');
        }
        $this->container['hp'] = $hp;

        return $this;
    }

    /**
     * Gets max_hp
     *
     * @return int
     */
    public function getMaxHp(): int
    {
        return $this->container['max_hp'];
    }

    /**
     * Sets max_hp
     *
     * @param int $max_hp Character max HP.
     *
     * @return $this
     */
    public function setMaxHp(int $max_hp): static
    {
        if (is_null($max_hp)) {
            throw new InvalidArgumentException('non-nullable max_hp cannot be null');
        }
        $this->container['max_hp'] = $max_hp;

        return $this;
    }

    /**
     * Gets haste
     *
     * @return int
     */
    public function getHaste(): int
    {
        return $this->container['haste'];
    }

    /**
     * Sets haste
     *
     * @param int $haste *Increase speed attack (reduce fight cooldown)
     *
     * @return $this
     */
    public function setHaste(int $haste): static
    {
        if (is_null($haste)) {
            throw new InvalidArgumentException('non-nullable haste cannot be null');
        }
        $this->container['haste'] = $haste;

        return $this;
    }

    /**
     * Gets critical_strike
     *
     * @return int
     */
    public function getCriticalStrike(): int
    {
        return $this->container['critical_strike'];
    }

    /**
     * Sets critical_strike
     *
     * @param int $critical_strike % Critical strike. Critical strikes adds 50% extra damage to an attack (1.5x).
     *
     * @return $this
     */
    public function setCriticalStrike(int $critical_strike): static
    {
        if (is_null($critical_strike)) {
            throw new InvalidArgumentException('non-nullable critical_strike cannot be null');
        }
        $this->container['critical_strike'] = $critical_strike;

        return $this;
    }

    /**
     * Gets wisdom
     *
     * @return int
     */
    public function getWisdom(): int
    {
        return $this->container['wisdom'];
    }

    /**
     * Sets wisdom
     *
     * @param int $wisdom Wisdom increases the amount of XP gained from fights and skills (1% extra per 10 wisdom).
     *
     * @return $this
     */
    public function setWisdom(int $wisdom): static
    {
        if (is_null($wisdom)) {
            throw new InvalidArgumentException('non-nullable wisdom cannot be null');
        }
        $this->container['wisdom'] = $wisdom;

        return $this;
    }

    /**
     * Gets prospecting
     *
     * @return int
     */
    public function getProspecting(): int
    {
        return $this->container['prospecting'];
    }

    /**
     * Sets prospecting
     *
     * @param int $prospecting Prospecting increases the chances of getting drops from fights and skills (1% extra per 10 PP).
     *
     * @return $this
     */
    public function setProspecting(int $prospecting): static
    {
        if (is_null($prospecting)) {
            throw new InvalidArgumentException('non-nullable prospecting cannot be null');
        }
        $this->container['prospecting'] = $prospecting;

        return $this;
    }

    /**
     * Gets initiative
     *
     * @return int
     */
    public function getInitiative(): int
    {
        return $this->container['initiative'];
    }

    /**
     * Sets initiative
     *
     * @param int $initiative Initiative determines turn order in combat. Higher initiative goes first.
     *
     * @return $this
     */
    public function setInitiative(int $initiative): static
    {
        if (is_null($initiative)) {
            throw new InvalidArgumentException('non-nullable initiative cannot be null');
        }
        $this->container['initiative'] = $initiative;

        return $this;
    }

    /**
     * Gets threat
     *
     * @return int
     */
    public function getThreat(): int
    {
        return $this->container['threat'];
    }

    /**
     * Sets threat
     *
     * @param int $threat Threat level affects monster targeting in multi-character combat.
     *
     * @return $this
     */
    public function setThreat(int $threat): static
    {
        if (is_null($threat)) {
            throw new InvalidArgumentException('non-nullable threat cannot be null');
        }
        $this->container['threat'] = $threat;

        return $this;
    }

    /**
     * Gets attack_fire
     *
     * @return int
     */
    public function getAttackFire(): int
    {
        return $this->container['attack_fire'];
    }

    /**
     * Sets attack_fire
     *
     * @param int $attack_fire Fire attack.
     *
     * @return $this
     */
    public function setAttackFire(int $attack_fire): static
    {
        if (is_null($attack_fire)) {
            throw new InvalidArgumentException('non-nullable attack_fire cannot be null');
        }
        $this->container['attack_fire'] = $attack_fire;

        return $this;
    }

    /**
     * Gets attack_earth
     *
     * @return int
     */
    public function getAttackEarth(): int
    {
        return $this->container['attack_earth'];
    }

    /**
     * Sets attack_earth
     *
     * @param int $attack_earth Earth attack.
     *
     * @return $this
     */
    public function setAttackEarth(int $attack_earth): static
    {
        if (is_null($attack_earth)) {
            throw new InvalidArgumentException('non-nullable attack_earth cannot be null');
        }
        $this->container['attack_earth'] = $attack_earth;

        return $this;
    }

    /**
     * Gets attack_water
     *
     * @return int
     */
    public function getAttackWater(): int
    {
        return $this->container['attack_water'];
    }

    /**
     * Sets attack_water
     *
     * @param int $attack_water Water attack.
     *
     * @return $this
     */
    public function setAttackWater(int $attack_water): static
    {
        if (is_null($attack_water)) {
            throw new InvalidArgumentException('non-nullable attack_water cannot be null');
        }
        $this->container['attack_water'] = $attack_water;

        return $this;
    }

    /**
     * Gets attack_air
     *
     * @return int
     */
    public function getAttackAir(): int
    {
        return $this->container['attack_air'];
    }

    /**
     * Sets attack_air
     *
     * @param int $attack_air Air attack.
     *
     * @return $this
     */
    public function setAttackAir(int $attack_air): static
    {
        if (is_null($attack_air)) {
            throw new InvalidArgumentException('non-nullable attack_air cannot be null');
        }
        $this->container['attack_air'] = $attack_air;

        return $this;
    }

    /**
     * Gets dmg
     *
     * @return int
     */
    public function getDmg(): int
    {
        return $this->container['dmg'];
    }

    /**
     * Sets dmg
     *
     * @param int $dmg % Damage. Damage increases your attack in all elements.
     *
     * @return $this
     */
    public function setDmg(int $dmg): static
    {
        if (is_null($dmg)) {
            throw new InvalidArgumentException('non-nullable dmg cannot be null');
        }
        $this->container['dmg'] = $dmg;

        return $this;
    }

    /**
     * Gets dmg_fire
     *
     * @return int
     */
    public function getDmgFire(): int
    {
        return $this->container['dmg_fire'];
    }

    /**
     * Sets dmg_fire
     *
     * @param int $dmg_fire % Fire damage. Damage increases your fire attack.
     *
     * @return $this
     */
    public function setDmgFire(int $dmg_fire): static
    {
        if (is_null($dmg_fire)) {
            throw new InvalidArgumentException('non-nullable dmg_fire cannot be null');
        }
        $this->container['dmg_fire'] = $dmg_fire;

        return $this;
    }

    /**
     * Gets dmg_earth
     *
     * @return int
     */
    public function getDmgEarth(): int
    {
        return $this->container['dmg_earth'];
    }

    /**
     * Sets dmg_earth
     *
     * @param int $dmg_earth % Earth damage. Damage increases your earth attack.
     *
     * @return $this
     */
    public function setDmgEarth(int $dmg_earth): static
    {
        if (is_null($dmg_earth)) {
            throw new InvalidArgumentException('non-nullable dmg_earth cannot be null');
        }
        $this->container['dmg_earth'] = $dmg_earth;

        return $this;
    }

    /**
     * Gets dmg_water
     *
     * @return int
     */
    public function getDmgWater(): int
    {
        return $this->container['dmg_water'];
    }

    /**
     * Sets dmg_water
     *
     * @param int $dmg_water % Water damage. Damage increases your water attack.
     *
     * @return $this
     */
    public function setDmgWater(int $dmg_water): static
    {
        if (is_null($dmg_water)) {
            throw new InvalidArgumentException('non-nullable dmg_water cannot be null');
        }
        $this->container['dmg_water'] = $dmg_water;

        return $this;
    }

    /**
     * Gets dmg_air
     *
     * @return int
     */
    public function getDmgAir(): int
    {
        return $this->container['dmg_air'];
    }

    /**
     * Sets dmg_air
     *
     * @param int $dmg_air % Air damage. Damage increases your air attack.
     *
     * @return $this
     */
    public function setDmgAir(int $dmg_air): static
    {
        if (is_null($dmg_air)) {
            throw new InvalidArgumentException('non-nullable dmg_air cannot be null');
        }
        $this->container['dmg_air'] = $dmg_air;

        return $this;
    }

    /**
     * Gets res_fire
     *
     * @return int
     */
    public function getResFire(): int
    {
        return $this->container['res_fire'];
    }

    /**
     * Sets res_fire
     *
     * @param int $res_fire % Fire resistance. Reduces fire attack.
     *
     * @return $this
     */
    public function setResFire(int $res_fire): static
    {
        if (is_null($res_fire)) {
            throw new InvalidArgumentException('non-nullable res_fire cannot be null');
        }
        $this->container['res_fire'] = $res_fire;

        return $this;
    }

    /**
     * Gets res_earth
     *
     * @return int
     */
    public function getResEarth(): int
    {
        return $this->container['res_earth'];
    }

    /**
     * Sets res_earth
     *
     * @param int $res_earth % Earth resistance. Reduces earth attack.
     *
     * @return $this
     */
    public function setResEarth(int $res_earth): static
    {
        if (is_null($res_earth)) {
            throw new InvalidArgumentException('non-nullable res_earth cannot be null');
        }
        $this->container['res_earth'] = $res_earth;

        return $this;
    }

    /**
     * Gets res_water
     *
     * @return int
     */
    public function getResWater(): int
    {
        return $this->container['res_water'];
    }

    /**
     * Sets res_water
     *
     * @param int $res_water % Water resistance. Reduces water attack.
     *
     * @return $this
     */
    public function setResWater(int $res_water): static
    {
        if (is_null($res_water)) {
            throw new InvalidArgumentException('non-nullable res_water cannot be null');
        }
        $this->container['res_water'] = $res_water;

        return $this;
    }

    /**
     * Gets res_air
     *
     * @return int
     */
    public function getResAir(): int
    {
        return $this->container['res_air'];
    }

    /**
     * Sets res_air
     *
     * @param int $res_air % Air resistance. Reduces air attack.
     *
     * @return $this
     */
    public function setResAir(int $res_air): static
    {
        if (is_null($res_air)) {
            throw new InvalidArgumentException('non-nullable res_air cannot be null');
        }
        $this->container['res_air'] = $res_air;

        return $this;
    }

    /**
     * Gets effects
     *
     * @return \\Kehet\ArtifactsMMO\\Model\StorageEffectSchema[]|null
     */
    public function getEffects(): ?array
    {
        return $this->container['effects'];
    }

    /**
     * Sets effects
     *
     * @param \\Kehet\ArtifactsMMO\\Model\StorageEffectSchema[]|null $effects List of active effects on the character.
     *
     * @return $this
     */
    public function setEffects(?array $effects): static
    {
        if (is_null($effects)) {
            throw new InvalidArgumentException('non-nullable effects cannot be null');
        }
        $this->container['effects'] = $effects;

        return $this;
    }

    /**
     * Gets x
     *
     * @return int
     */
    public function getX(): int
    {
        return $this->container['x'];
    }

    /**
     * Sets x
     *
     * @param int $x Character x coordinate.
     *
     * @return $this
     */
    public function setX(int $x): static
    {
        if (is_null($x)) {
            throw new InvalidArgumentException('non-nullable x cannot be null');
        }
        $this->container['x'] = $x;

        return $this;
    }

    /**
     * Gets y
     *
     * @return int
     */
    public function getY(): int
    {
        return $this->container['y'];
    }

    /**
     * Sets y
     *
     * @param int $y Character y coordinate.
     *
     * @return $this
     */
    public function setY(int $y): static
    {
        if (is_null($y)) {
            throw new InvalidArgumentException('non-nullable y cannot be null');
        }
        $this->container['y'] = $y;

        return $this;
    }

    /**
     * Gets layer
     *
     * @return \\Kehet\ArtifactsMMO\\Model\MapLayer
     */
    public function getLayer(): \\Kehet\ArtifactsMMO\\Model\MapLayer
    {
        return $this->container['layer'];
    }

    /**
     * Sets layer
     *
     * @param \\Kehet\ArtifactsMMO\\Model\MapLayer $layer Character current layer.
     *
     * @return $this
     */
    public function setLayer(\\Kehet\ArtifactsMMO\\Model\MapLayer $layer): static
    {
        if (is_null($layer)) {
            throw new InvalidArgumentException('non-nullable layer cannot be null');
        }
        $this->container['layer'] = $layer;

        return $this;
    }

    /**
     * Gets map_id
     *
     * @return int
     */
    public function getMapId(): int
    {
        return $this->container['map_id'];
    }

    /**
     * Sets map_id
     *
     * @param int $map_id Character current map ID.
     *
     * @return $this
     */
    public function setMapId(int $map_id): static
    {
        if (is_null($map_id)) {
            throw new InvalidArgumentException('non-nullable map_id cannot be null');
        }
        $this->container['map_id'] = $map_id;

        return $this;
    }

    /**
     * Gets cooldown
     *
     * @return int
     */
    public function getCooldown(): int
    {
        return $this->container['cooldown'];
    }

    /**
     * Sets cooldown
     *
     * @param int $cooldown Cooldown in seconds.
     *
     * @return $this
     */
    public function setCooldown(int $cooldown): static
    {
        if (is_null($cooldown)) {
            throw new InvalidArgumentException('non-nullable cooldown cannot be null');
        }
        $this->container['cooldown'] = $cooldown;

        return $this;
    }

    /**
     * Gets cooldown_expiration
     *
     * @return \DateTime|null
     */
    public function getCooldownExpiration(): ?\DateTime
    {
        return $this->container['cooldown_expiration'];
    }

    /**
     * Sets cooldown_expiration
     *
     * @param \DateTime|null $cooldown_expiration Datetime Cooldown expiration.
     *
     * @return $this
     */
    public function setCooldownExpiration(?\DateTime $cooldown_expiration): static
    {
        if (is_null($cooldown_expiration)) {
            throw new InvalidArgumentException('non-nullable cooldown_expiration cannot be null');
        }
        $this->container['cooldown_expiration'] = $cooldown_expiration;

        return $this;
    }

    /**
     * Gets weapon_slot
     *
     * @return string
     */
    public function getWeaponSlot(): string
    {
        return $this->container['weapon_slot'];
    }

    /**
     * Sets weapon_slot
     *
     * @param string $weapon_slot Weapon slot.
     *
     * @return $this
     */
    public function setWeaponSlot(string $weapon_slot): static
    {
        if (is_null($weapon_slot)) {
            throw new InvalidArgumentException('non-nullable weapon_slot cannot be null');
        }
        $this->container['weapon_slot'] = $weapon_slot;

        return $this;
    }

    /**
     * Gets rune_slot
     *
     * @return string
     */
    public function getRuneSlot(): string
    {
        return $this->container['rune_slot'];
    }

    /**
     * Sets rune_slot
     *
     * @param string $rune_slot Rune slot.
     *
     * @return $this
     */
    public function setRuneSlot(string $rune_slot): static
    {
        if (is_null($rune_slot)) {
            throw new InvalidArgumentException('non-nullable rune_slot cannot be null');
        }
        $this->container['rune_slot'] = $rune_slot;

        return $this;
    }

    /**
     * Gets shield_slot
     *
     * @return string
     */
    public function getShieldSlot(): string
    {
        return $this->container['shield_slot'];
    }

    /**
     * Sets shield_slot
     *
     * @param string $shield_slot Shield slot.
     *
     * @return $this
     */
    public function setShieldSlot(string $shield_slot): static
    {
        if (is_null($shield_slot)) {
            throw new InvalidArgumentException('non-nullable shield_slot cannot be null');
        }
        $this->container['shield_slot'] = $shield_slot;

        return $this;
    }

    /**
     * Gets helmet_slot
     *
     * @return string
     */
    public function getHelmetSlot(): string
    {
        return $this->container['helmet_slot'];
    }

    /**
     * Sets helmet_slot
     *
     * @param string $helmet_slot Helmet slot.
     *
     * @return $this
     */
    public function setHelmetSlot(string $helmet_slot): static
    {
        if (is_null($helmet_slot)) {
            throw new InvalidArgumentException('non-nullable helmet_slot cannot be null');
        }
        $this->container['helmet_slot'] = $helmet_slot;

        return $this;
    }

    /**
     * Gets body_armor_slot
     *
     * @return string
     */
    public function getBodyArmorSlot(): string
    {
        return $this->container['body_armor_slot'];
    }

    /**
     * Sets body_armor_slot
     *
     * @param string $body_armor_slot Body armor slot.
     *
     * @return $this
     */
    public function setBodyArmorSlot(string $body_armor_slot): static
    {
        if (is_null($body_armor_slot)) {
            throw new InvalidArgumentException('non-nullable body_armor_slot cannot be null');
        }
        $this->container['body_armor_slot'] = $body_armor_slot;

        return $this;
    }

    /**
     * Gets leg_armor_slot
     *
     * @return string
     */
    public function getLegArmorSlot(): string
    {
        return $this->container['leg_armor_slot'];
    }

    /**
     * Sets leg_armor_slot
     *
     * @param string $leg_armor_slot Leg armor slot.
     *
     * @return $this
     */
    public function setLegArmorSlot(string $leg_armor_slot): static
    {
        if (is_null($leg_armor_slot)) {
            throw new InvalidArgumentException('non-nullable leg_armor_slot cannot be null');
        }
        $this->container['leg_armor_slot'] = $leg_armor_slot;

        return $this;
    }

    /**
     * Gets boots_slot
     *
     * @return string
     */
    public function getBootsSlot(): string
    {
        return $this->container['boots_slot'];
    }

    /**
     * Sets boots_slot
     *
     * @param string $boots_slot Boots slot.
     *
     * @return $this
     */
    public function setBootsSlot(string $boots_slot): static
    {
        if (is_null($boots_slot)) {
            throw new InvalidArgumentException('non-nullable boots_slot cannot be null');
        }
        $this->container['boots_slot'] = $boots_slot;

        return $this;
    }

    /**
     * Gets ring1_slot
     *
     * @return string
     */
    public function getRing1Slot(): string
    {
        return $this->container['ring1_slot'];
    }

    /**
     * Sets ring1_slot
     *
     * @param string $ring1_slot Ring 1 slot.
     *
     * @return $this
     */
    public function setRing1Slot(string $ring1_slot): static
    {
        if (is_null($ring1_slot)) {
            throw new InvalidArgumentException('non-nullable ring1_slot cannot be null');
        }
        $this->container['ring1_slot'] = $ring1_slot;

        return $this;
    }

    /**
     * Gets ring2_slot
     *
     * @return string
     */
    public function getRing2Slot(): string
    {
        return $this->container['ring2_slot'];
    }

    /**
     * Sets ring2_slot
     *
     * @param string $ring2_slot Ring 2 slot.
     *
     * @return $this
     */
    public function setRing2Slot(string $ring2_slot): static
    {
        if (is_null($ring2_slot)) {
            throw new InvalidArgumentException('non-nullable ring2_slot cannot be null');
        }
        $this->container['ring2_slot'] = $ring2_slot;

        return $this;
    }

    /**
     * Gets amulet_slot
     *
     * @return string
     */
    public function getAmuletSlot(): string
    {
        return $this->container['amulet_slot'];
    }

    /**
     * Sets amulet_slot
     *
     * @param string $amulet_slot Amulet slot.
     *
     * @return $this
     */
    public function setAmuletSlot(string $amulet_slot): static
    {
        if (is_null($amulet_slot)) {
            throw new InvalidArgumentException('non-nullable amulet_slot cannot be null');
        }
        $this->container['amulet_slot'] = $amulet_slot;

        return $this;
    }

    /**
     * Gets artifact1_slot
     *
     * @return string
     */
    public function getArtifact1Slot(): string
    {
        return $this->container['artifact1_slot'];
    }

    /**
     * Sets artifact1_slot
     *
     * @param string $artifact1_slot Artifact 1 slot.
     *
     * @return $this
     */
    public function setArtifact1Slot(string $artifact1_slot): static
    {
        if (is_null($artifact1_slot)) {
            throw new InvalidArgumentException('non-nullable artifact1_slot cannot be null');
        }
        $this->container['artifact1_slot'] = $artifact1_slot;

        return $this;
    }

    /**
     * Gets artifact2_slot
     *
     * @return string
     */
    public function getArtifact2Slot(): string
    {
        return $this->container['artifact2_slot'];
    }

    /**
     * Sets artifact2_slot
     *
     * @param string $artifact2_slot Artifact 2 slot.
     *
     * @return $this
     */
    public function setArtifact2Slot(string $artifact2_slot): static
    {
        if (is_null($artifact2_slot)) {
            throw new InvalidArgumentException('non-nullable artifact2_slot cannot be null');
        }
        $this->container['artifact2_slot'] = $artifact2_slot;

        return $this;
    }

    /**
     * Gets artifact3_slot
     *
     * @return string
     */
    public function getArtifact3Slot(): string
    {
        return $this->container['artifact3_slot'];
    }

    /**
     * Sets artifact3_slot
     *
     * @param string $artifact3_slot Artifact 3 slot.
     *
     * @return $this
     */
    public function setArtifact3Slot(string $artifact3_slot): static
    {
        if (is_null($artifact3_slot)) {
            throw new InvalidArgumentException('non-nullable artifact3_slot cannot be null');
        }
        $this->container['artifact3_slot'] = $artifact3_slot;

        return $this;
    }

    /**
     * Gets utility1_slot
     *
     * @return string
     */
    public function getUtility1Slot(): string
    {
        return $this->container['utility1_slot'];
    }

    /**
     * Sets utility1_slot
     *
     * @param string $utility1_slot Utility 1 slot.
     *
     * @return $this
     */
    public function setUtility1Slot(string $utility1_slot): static
    {
        if (is_null($utility1_slot)) {
            throw new InvalidArgumentException('non-nullable utility1_slot cannot be null');
        }
        $this->container['utility1_slot'] = $utility1_slot;

        return $this;
    }

    /**
     * Gets utility1_slot_quantity
     *
     * @return int
     */
    public function getUtility1SlotQuantity(): int
    {
        return $this->container['utility1_slot_quantity'];
    }

    /**
     * Sets utility1_slot_quantity
     *
     * @param int $utility1_slot_quantity Utility 1 quantity.
     *
     * @return $this
     */
    public function setUtility1SlotQuantity(int $utility1_slot_quantity): static
    {
        if (is_null($utility1_slot_quantity)) {
            throw new InvalidArgumentException('non-nullable utility1_slot_quantity cannot be null');
        }

        if (($utility1_slot_quantity < 0)) {
            throw new InvalidArgumentException('invalid value for $utility1_slot_quantity when calling CharacterSchema., must be bigger than or equal to 0.');
        }

        $this->container['utility1_slot_quantity'] = $utility1_slot_quantity;

        return $this;
    }

    /**
     * Gets utility2_slot
     *
     * @return string
     */
    public function getUtility2Slot(): string
    {
        return $this->container['utility2_slot'];
    }

    /**
     * Sets utility2_slot
     *
     * @param string $utility2_slot Utility 2 slot.
     *
     * @return $this
     */
    public function setUtility2Slot(string $utility2_slot): static
    {
        if (is_null($utility2_slot)) {
            throw new InvalidArgumentException('non-nullable utility2_slot cannot be null');
        }
        $this->container['utility2_slot'] = $utility2_slot;

        return $this;
    }

    /**
     * Gets utility2_slot_quantity
     *
     * @return int
     */
    public function getUtility2SlotQuantity(): int
    {
        return $this->container['utility2_slot_quantity'];
    }

    /**
     * Sets utility2_slot_quantity
     *
     * @param int $utility2_slot_quantity Utility 2 quantity.
     *
     * @return $this
     */
    public function setUtility2SlotQuantity(int $utility2_slot_quantity): static
    {
        if (is_null($utility2_slot_quantity)) {
            throw new InvalidArgumentException('non-nullable utility2_slot_quantity cannot be null');
        }

        if (($utility2_slot_quantity < 0)) {
            throw new InvalidArgumentException('invalid value for $utility2_slot_quantity when calling CharacterSchema., must be bigger than or equal to 0.');
        }

        $this->container['utility2_slot_quantity'] = $utility2_slot_quantity;

        return $this;
    }

    /**
     * Gets bag_slot
     *
     * @return string
     */
    public function getBagSlot(): string
    {
        return $this->container['bag_slot'];
    }

    /**
     * Sets bag_slot
     *
     * @param string $bag_slot Bag slot.
     *
     * @return $this
     */
    public function setBagSlot(string $bag_slot): static
    {
        if (is_null($bag_slot)) {
            throw new InvalidArgumentException('non-nullable bag_slot cannot be null');
        }
        $this->container['bag_slot'] = $bag_slot;

        return $this;
    }

    /**
     * Gets task
     *
     * @return string
     */
    public function getTask(): string
    {
        return $this->container['task'];
    }

    /**
     * Sets task
     *
     * @param string $task Task in progress.
     *
     * @return $this
     */
    public function setTask(string $task): static
    {
        if (is_null($task)) {
            throw new InvalidArgumentException('non-nullable task cannot be null');
        }
        $this->container['task'] = $task;

        return $this;
    }

    /**
     * Gets task_type
     *
     * @return string
     */
    public function getTaskType(): string
    {
        return $this->container['task_type'];
    }

    /**
     * Sets task_type
     *
     * @param string $task_type Task type.
     *
     * @return $this
     */
    public function setTaskType(string $task_type): static
    {
        if (is_null($task_type)) {
            throw new InvalidArgumentException('non-nullable task_type cannot be null');
        }
        $this->container['task_type'] = $task_type;

        return $this;
    }

    /**
     * Gets task_progress
     *
     * @return int
     */
    public function getTaskProgress(): int
    {
        return $this->container['task_progress'];
    }

    /**
     * Sets task_progress
     *
     * @param int $task_progress Task progression.
     *
     * @return $this
     */
    public function setTaskProgress(int $task_progress): static
    {
        if (is_null($task_progress)) {
            throw new InvalidArgumentException('non-nullable task_progress cannot be null');
        }
        $this->container['task_progress'] = $task_progress;

        return $this;
    }

    /**
     * Gets task_total
     *
     * @return int
     */
    public function getTaskTotal(): int
    {
        return $this->container['task_total'];
    }

    /**
     * Sets task_total
     *
     * @param int $task_total Task total objective.
     *
     * @return $this
     */
    public function setTaskTotal(int $task_total): static
    {
        if (is_null($task_total)) {
            throw new InvalidArgumentException('non-nullable task_total cannot be null');
        }
        $this->container['task_total'] = $task_total;

        return $this;
    }

    /**
     * Gets inventory_max_items
     *
     * @return int
     */
    public function getInventoryMaxItems(): int
    {
        return $this->container['inventory_max_items'];
    }

    /**
     * Sets inventory_max_items
     *
     * @param int $inventory_max_items Inventory max items.
     *
     * @return $this
     */
    public function setInventoryMaxItems(int $inventory_max_items): static
    {
        if (is_null($inventory_max_items)) {
            throw new InvalidArgumentException('non-nullable inventory_max_items cannot be null');
        }
        $this->container['inventory_max_items'] = $inventory_max_items;

        return $this;
    }

    /**
     * Gets inventory
     *
     * @return \\Kehet\ArtifactsMMO\\Model\InventorySlot[]|null
     */
    public function getInventory(): ?array
    {
        return $this->container['inventory'];
    }

    /**
     * Sets inventory
     *
     * @param \\Kehet\ArtifactsMMO\\Model\InventorySlot[]|null $inventory List of inventory slots.
     *
     * @return $this
     */
    public function setInventory(?array $inventory): static
    {
        if (is_null($inventory)) {
            throw new InvalidArgumentException('non-nullable inventory cannot be null');
        }
        $this->container['inventory'] = $inventory;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


