<?php

/**
 * CharacterLeaderboardSchema
 *
 * PHP version 8.1
 *
 * @package  Kehet\ArtifactsMMO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kehet\ArtifactsMMO\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Kehet\ArtifactsMMO\ObjectSerializer;

/**
 * CharacterLeaderboardSchema Class Doc Comment
 *
 * @package  Kehet\ArtifactsMMO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CharacterLeaderboardSchema implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'CharacterLeaderboardSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'position' => 'int',
        'name' => 'string',
        'account' => 'string',
        'status' => '\Kehet\ArtifactsMMO\Model\AccountStatus',
        'skin' => 'string',
        'level' => 'int',
        'total_xp' => 'int',
        'mining_level' => 'int',
        'mining_total_xp' => 'int',
        'woodcutting_level' => 'int',
        'woodcutting_total_xp' => 'int',
        'fishing_level' => 'int',
        'fishing_total_xp' => 'int',
        'weaponcrafting_level' => 'int',
        'weaponcrafting_total_xp' => 'int',
        'gearcrafting_level' => 'int',
        'gearcrafting_total_xp' => 'int',
        'jewelrycrafting_level' => 'int',
        'jewelrycrafting_total_xp' => 'int',
        'cooking_level' => 'int',
        'cooking_total_xp' => 'int',
        'alchemy_level' => 'int',
        'alchemy_total_xp' => 'int',
        'gold' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'position' => null,
        'name' => null,
        'account' => null,
        'status' => null,
        'skin' => null,
        'level' => null,
        'total_xp' => null,
        'mining_level' => null,
        'mining_total_xp' => null,
        'woodcutting_level' => null,
        'woodcutting_total_xp' => null,
        'fishing_level' => null,
        'fishing_total_xp' => null,
        'weaponcrafting_level' => null,
        'weaponcrafting_total_xp' => null,
        'gearcrafting_level' => null,
        'gearcrafting_total_xp' => null,
        'jewelrycrafting_level' => null,
        'jewelrycrafting_total_xp' => null,
        'cooking_level' => null,
        'cooking_total_xp' => null,
        'alchemy_level' => null,
        'alchemy_total_xp' => null,
        'gold' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'position' => false,
        'name' => false,
        'account' => false,
        'status' => false,
        'skin' => false,
        'level' => false,
        'total_xp' => false,
        'mining_level' => false,
        'mining_total_xp' => false,
        'woodcutting_level' => false,
        'woodcutting_total_xp' => false,
        'fishing_level' => false,
        'fishing_total_xp' => false,
        'weaponcrafting_level' => false,
        'weaponcrafting_total_xp' => false,
        'gearcrafting_level' => false,
        'gearcrafting_total_xp' => false,
        'jewelrycrafting_level' => false,
        'jewelrycrafting_total_xp' => false,
        'cooking_level' => false,
        'cooking_total_xp' => false,
        'alchemy_level' => false,
        'alchemy_total_xp' => false,
        'gold' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'position' => 'position',
        'name' => 'name',
        'account' => 'account',
        'status' => 'status',
        'skin' => 'skin',
        'level' => 'level',
        'total_xp' => 'total_xp',
        'mining_level' => 'mining_level',
        'mining_total_xp' => 'mining_total_xp',
        'woodcutting_level' => 'woodcutting_level',
        'woodcutting_total_xp' => 'woodcutting_total_xp',
        'fishing_level' => 'fishing_level',
        'fishing_total_xp' => 'fishing_total_xp',
        'weaponcrafting_level' => 'weaponcrafting_level',
        'weaponcrafting_total_xp' => 'weaponcrafting_total_xp',
        'gearcrafting_level' => 'gearcrafting_level',
        'gearcrafting_total_xp' => 'gearcrafting_total_xp',
        'jewelrycrafting_level' => 'jewelrycrafting_level',
        'jewelrycrafting_total_xp' => 'jewelrycrafting_total_xp',
        'cooking_level' => 'cooking_level',
        'cooking_total_xp' => 'cooking_total_xp',
        'alchemy_level' => 'alchemy_level',
        'alchemy_total_xp' => 'alchemy_total_xp',
        'gold' => 'gold'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'position' => 'setPosition',
        'name' => 'setName',
        'account' => 'setAccount',
        'status' => 'setStatus',
        'skin' => 'setSkin',
        'level' => 'setLevel',
        'total_xp' => 'setTotalXp',
        'mining_level' => 'setMiningLevel',
        'mining_total_xp' => 'setMiningTotalXp',
        'woodcutting_level' => 'setWoodcuttingLevel',
        'woodcutting_total_xp' => 'setWoodcuttingTotalXp',
        'fishing_level' => 'setFishingLevel',
        'fishing_total_xp' => 'setFishingTotalXp',
        'weaponcrafting_level' => 'setWeaponcraftingLevel',
        'weaponcrafting_total_xp' => 'setWeaponcraftingTotalXp',
        'gearcrafting_level' => 'setGearcraftingLevel',
        'gearcrafting_total_xp' => 'setGearcraftingTotalXp',
        'jewelrycrafting_level' => 'setJewelrycraftingLevel',
        'jewelrycrafting_total_xp' => 'setJewelrycraftingTotalXp',
        'cooking_level' => 'setCookingLevel',
        'cooking_total_xp' => 'setCookingTotalXp',
        'alchemy_level' => 'setAlchemyLevel',
        'alchemy_total_xp' => 'setAlchemyTotalXp',
        'gold' => 'setGold'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'position' => 'getPosition',
        'name' => 'getName',
        'account' => 'getAccount',
        'status' => 'getStatus',
        'skin' => 'getSkin',
        'level' => 'getLevel',
        'total_xp' => 'getTotalXp',
        'mining_level' => 'getMiningLevel',
        'mining_total_xp' => 'getMiningTotalXp',
        'woodcutting_level' => 'getWoodcuttingLevel',
        'woodcutting_total_xp' => 'getWoodcuttingTotalXp',
        'fishing_level' => 'getFishingLevel',
        'fishing_total_xp' => 'getFishingTotalXp',
        'weaponcrafting_level' => 'getWeaponcraftingLevel',
        'weaponcrafting_total_xp' => 'getWeaponcraftingTotalXp',
        'gearcrafting_level' => 'getGearcraftingLevel',
        'gearcrafting_total_xp' => 'getGearcraftingTotalXp',
        'jewelrycrafting_level' => 'getJewelrycraftingLevel',
        'jewelrycrafting_total_xp' => 'getJewelrycraftingTotalXp',
        'cooking_level' => 'getCookingLevel',
        'cooking_total_xp' => 'getCookingTotalXp',
        'alchemy_level' => 'getAlchemyLevel',
        'alchemy_total_xp' => 'getAlchemyTotalXp',
        'gold' => 'getGold'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('position', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('account', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('skin', $data ?? [], null);
        $this->setIfExists('level', $data ?? [], null);
        $this->setIfExists('total_xp', $data ?? [], null);
        $this->setIfExists('mining_level', $data ?? [], null);
        $this->setIfExists('mining_total_xp', $data ?? [], null);
        $this->setIfExists('woodcutting_level', $data ?? [], null);
        $this->setIfExists('woodcutting_total_xp', $data ?? [], null);
        $this->setIfExists('fishing_level', $data ?? [], null);
        $this->setIfExists('fishing_total_xp', $data ?? [], null);
        $this->setIfExists('weaponcrafting_level', $data ?? [], null);
        $this->setIfExists('weaponcrafting_total_xp', $data ?? [], null);
        $this->setIfExists('gearcrafting_level', $data ?? [], null);
        $this->setIfExists('gearcrafting_total_xp', $data ?? [], null);
        $this->setIfExists('jewelrycrafting_level', $data ?? [], null);
        $this->setIfExists('jewelrycrafting_total_xp', $data ?? [], null);
        $this->setIfExists('cooking_level', $data ?? [], null);
        $this->setIfExists('cooking_total_xp', $data ?? [], null);
        $this->setIfExists('alchemy_level', $data ?? [], null);
        $this->setIfExists('alchemy_total_xp', $data ?? [], null);
        $this->setIfExists('gold', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['position'] === null) {
            $invalidProperties[] = "'position' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['account'] === null) {
            $invalidProperties[] = "'account' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['skin'] === null) {
            $invalidProperties[] = "'skin' can't be null";
        }
        if ($this->container['level'] === null) {
            $invalidProperties[] = "'level' can't be null";
        }
        if ($this->container['total_xp'] === null) {
            $invalidProperties[] = "'total_xp' can't be null";
        }
        if ($this->container['mining_level'] === null) {
            $invalidProperties[] = "'mining_level' can't be null";
        }
        if ($this->container['mining_total_xp'] === null) {
            $invalidProperties[] = "'mining_total_xp' can't be null";
        }
        if ($this->container['woodcutting_level'] === null) {
            $invalidProperties[] = "'woodcutting_level' can't be null";
        }
        if ($this->container['woodcutting_total_xp'] === null) {
            $invalidProperties[] = "'woodcutting_total_xp' can't be null";
        }
        if ($this->container['fishing_level'] === null) {
            $invalidProperties[] = "'fishing_level' can't be null";
        }
        if ($this->container['fishing_total_xp'] === null) {
            $invalidProperties[] = "'fishing_total_xp' can't be null";
        }
        if ($this->container['weaponcrafting_level'] === null) {
            $invalidProperties[] = "'weaponcrafting_level' can't be null";
        }
        if ($this->container['weaponcrafting_total_xp'] === null) {
            $invalidProperties[] = "'weaponcrafting_total_xp' can't be null";
        }
        if ($this->container['gearcrafting_level'] === null) {
            $invalidProperties[] = "'gearcrafting_level' can't be null";
        }
        if ($this->container['gearcrafting_total_xp'] === null) {
            $invalidProperties[] = "'gearcrafting_total_xp' can't be null";
        }
        if ($this->container['jewelrycrafting_level'] === null) {
            $invalidProperties[] = "'jewelrycrafting_level' can't be null";
        }
        if ($this->container['jewelrycrafting_total_xp'] === null) {
            $invalidProperties[] = "'jewelrycrafting_total_xp' can't be null";
        }
        if ($this->container['cooking_level'] === null) {
            $invalidProperties[] = "'cooking_level' can't be null";
        }
        if ($this->container['cooking_total_xp'] === null) {
            $invalidProperties[] = "'cooking_total_xp' can't be null";
        }
        if ($this->container['alchemy_level'] === null) {
            $invalidProperties[] = "'alchemy_level' can't be null";
        }
        if ($this->container['alchemy_total_xp'] === null) {
            $invalidProperties[] = "'alchemy_total_xp' can't be null";
        }
        if ($this->container['gold'] === null) {
            $invalidProperties[] = "'gold' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets position
     *
     * @return int
     */
    public function getPosition(): int
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param int $position Position in the leaderboard.
     *
     * @return $this
     */
    public function setPosition(int $position): static
    {
        if (is_null($position)) {
            throw new InvalidArgumentException('non-nullable position cannot be null');
        }
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Character name.
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets account
     *
     * @return string
     */
    public function getAccount(): string
    {
        return $this->container['account'];
    }

    /**
     * Sets account
     *
     * @param string $account Account name.
     *
     * @return $this
     */
    public function setAccount(string $account): static
    {
        if (is_null($account)) {
            throw new InvalidArgumentException('non-nullable account cannot be null');
        }
        $this->container['account'] = $account;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Kehet\ArtifactsMMO\Model\AccountStatus
     */
    public function getStatus(): \Kehet\ArtifactsMMO\Model\AccountStatus
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Kehet\ArtifactsMMO\Model\AccountStatus $status Member status.
     *
     * @return $this
     */
    public function setStatus(\Kehet\ArtifactsMMO\Model\AccountStatus $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets skin
     *
     * @return string
     */
    public function getSkin(): string
    {
        return $this->container['skin'];
    }

    /**
     * Sets skin
     *
     * @param string $skin Character skin code.
     *
     * @return $this
     */
    public function setSkin(string $skin): static
    {
        if (is_null($skin)) {
            throw new InvalidArgumentException('non-nullable skin cannot be null');
        }
        $this->container['skin'] = $skin;

        return $this;
    }

    /**
     * Gets level
     *
     * @return int
     */
    public function getLevel(): int
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param int $level Combat level.
     *
     * @return $this
     */
    public function setLevel(int $level): static
    {
        if (is_null($level)) {
            throw new InvalidArgumentException('non-nullable level cannot be null');
        }
        $this->container['level'] = $level;

        return $this;
    }

    /**
     * Gets total_xp
     *
     * @return int
     */
    public function getTotalXp(): int
    {
        return $this->container['total_xp'];
    }

    /**
     * Sets total_xp
     *
     * @param int $total_xp Total XP of your character.
     *
     * @return $this
     */
    public function setTotalXp(int $total_xp): static
    {
        if (is_null($total_xp)) {
            throw new InvalidArgumentException('non-nullable total_xp cannot be null');
        }
        $this->container['total_xp'] = $total_xp;

        return $this;
    }

    /**
     * Gets mining_level
     *
     * @return int
     */
    public function getMiningLevel(): int
    {
        return $this->container['mining_level'];
    }

    /**
     * Sets mining_level
     *
     * @param int $mining_level Mining level.
     *
     * @return $this
     */
    public function setMiningLevel(int $mining_level): static
    {
        if (is_null($mining_level)) {
            throw new InvalidArgumentException('non-nullable mining_level cannot be null');
        }
        $this->container['mining_level'] = $mining_level;

        return $this;
    }

    /**
     * Gets mining_total_xp
     *
     * @return int
     */
    public function getMiningTotalXp(): int
    {
        return $this->container['mining_total_xp'];
    }

    /**
     * Sets mining_total_xp
     *
     * @param int $mining_total_xp Mining total xp.
     *
     * @return $this
     */
    public function setMiningTotalXp(int $mining_total_xp): static
    {
        if (is_null($mining_total_xp)) {
            throw new InvalidArgumentException('non-nullable mining_total_xp cannot be null');
        }
        $this->container['mining_total_xp'] = $mining_total_xp;

        return $this;
    }

    /**
     * Gets woodcutting_level
     *
     * @return int
     */
    public function getWoodcuttingLevel(): int
    {
        return $this->container['woodcutting_level'];
    }

    /**
     * Sets woodcutting_level
     *
     * @param int $woodcutting_level Woodcutting level.
     *
     * @return $this
     */
    public function setWoodcuttingLevel(int $woodcutting_level): static
    {
        if (is_null($woodcutting_level)) {
            throw new InvalidArgumentException('non-nullable woodcutting_level cannot be null');
        }
        $this->container['woodcutting_level'] = $woodcutting_level;

        return $this;
    }

    /**
     * Gets woodcutting_total_xp
     *
     * @return int
     */
    public function getWoodcuttingTotalXp(): int
    {
        return $this->container['woodcutting_total_xp'];
    }

    /**
     * Sets woodcutting_total_xp
     *
     * @param int $woodcutting_total_xp Woodcutting total xp.
     *
     * @return $this
     */
    public function setWoodcuttingTotalXp(int $woodcutting_total_xp): static
    {
        if (is_null($woodcutting_total_xp)) {
            throw new InvalidArgumentException('non-nullable woodcutting_total_xp cannot be null');
        }
        $this->container['woodcutting_total_xp'] = $woodcutting_total_xp;

        return $this;
    }

    /**
     * Gets fishing_level
     *
     * @return int
     */
    public function getFishingLevel(): int
    {
        return $this->container['fishing_level'];
    }

    /**
     * Sets fishing_level
     *
     * @param int $fishing_level Fishing level.
     *
     * @return $this
     */
    public function setFishingLevel(int $fishing_level): static
    {
        if (is_null($fishing_level)) {
            throw new InvalidArgumentException('non-nullable fishing_level cannot be null');
        }
        $this->container['fishing_level'] = $fishing_level;

        return $this;
    }

    /**
     * Gets fishing_total_xp
     *
     * @return int
     */
    public function getFishingTotalXp(): int
    {
        return $this->container['fishing_total_xp'];
    }

    /**
     * Sets fishing_total_xp
     *
     * @param int $fishing_total_xp Fishing total xp.
     *
     * @return $this
     */
    public function setFishingTotalXp(int $fishing_total_xp): static
    {
        if (is_null($fishing_total_xp)) {
            throw new InvalidArgumentException('non-nullable fishing_total_xp cannot be null');
        }
        $this->container['fishing_total_xp'] = $fishing_total_xp;

        return $this;
    }

    /**
     * Gets weaponcrafting_level
     *
     * @return int
     */
    public function getWeaponcraftingLevel(): int
    {
        return $this->container['weaponcrafting_level'];
    }

    /**
     * Sets weaponcrafting_level
     *
     * @param int $weaponcrafting_level Weaponcrafting level.
     *
     * @return $this
     */
    public function setWeaponcraftingLevel(int $weaponcrafting_level): static
    {
        if (is_null($weaponcrafting_level)) {
            throw new InvalidArgumentException('non-nullable weaponcrafting_level cannot be null');
        }
        $this->container['weaponcrafting_level'] = $weaponcrafting_level;

        return $this;
    }

    /**
     * Gets weaponcrafting_total_xp
     *
     * @return int
     */
    public function getWeaponcraftingTotalXp(): int
    {
        return $this->container['weaponcrafting_total_xp'];
    }

    /**
     * Sets weaponcrafting_total_xp
     *
     * @param int $weaponcrafting_total_xp Weaponcrafting total xp.
     *
     * @return $this
     */
    public function setWeaponcraftingTotalXp(int $weaponcrafting_total_xp): static
    {
        if (is_null($weaponcrafting_total_xp)) {
            throw new InvalidArgumentException('non-nullable weaponcrafting_total_xp cannot be null');
        }
        $this->container['weaponcrafting_total_xp'] = $weaponcrafting_total_xp;

        return $this;
    }

    /**
     * Gets gearcrafting_level
     *
     * @return int
     */
    public function getGearcraftingLevel(): int
    {
        return $this->container['gearcrafting_level'];
    }

    /**
     * Sets gearcrafting_level
     *
     * @param int $gearcrafting_level Gearcrafting level.
     *
     * @return $this
     */
    public function setGearcraftingLevel(int $gearcrafting_level): static
    {
        if (is_null($gearcrafting_level)) {
            throw new InvalidArgumentException('non-nullable gearcrafting_level cannot be null');
        }
        $this->container['gearcrafting_level'] = $gearcrafting_level;

        return $this;
    }

    /**
     * Gets gearcrafting_total_xp
     *
     * @return int
     */
    public function getGearcraftingTotalXp(): int
    {
        return $this->container['gearcrafting_total_xp'];
    }

    /**
     * Sets gearcrafting_total_xp
     *
     * @param int $gearcrafting_total_xp Gearcrafting total xp.
     *
     * @return $this
     */
    public function setGearcraftingTotalXp(int $gearcrafting_total_xp): static
    {
        if (is_null($gearcrafting_total_xp)) {
            throw new InvalidArgumentException('non-nullable gearcrafting_total_xp cannot be null');
        }
        $this->container['gearcrafting_total_xp'] = $gearcrafting_total_xp;

        return $this;
    }

    /**
     * Gets jewelrycrafting_level
     *
     * @return int
     */
    public function getJewelrycraftingLevel(): int
    {
        return $this->container['jewelrycrafting_level'];
    }

    /**
     * Sets jewelrycrafting_level
     *
     * @param int $jewelrycrafting_level Jewelrycrafting level.
     *
     * @return $this
     */
    public function setJewelrycraftingLevel(int $jewelrycrafting_level): static
    {
        if (is_null($jewelrycrafting_level)) {
            throw new InvalidArgumentException('non-nullable jewelrycrafting_level cannot be null');
        }
        $this->container['jewelrycrafting_level'] = $jewelrycrafting_level;

        return $this;
    }

    /**
     * Gets jewelrycrafting_total_xp
     *
     * @return int
     */
    public function getJewelrycraftingTotalXp(): int
    {
        return $this->container['jewelrycrafting_total_xp'];
    }

    /**
     * Sets jewelrycrafting_total_xp
     *
     * @param int $jewelrycrafting_total_xp Jewelrycrafting total xp.
     *
     * @return $this
     */
    public function setJewelrycraftingTotalXp(int $jewelrycrafting_total_xp): static
    {
        if (is_null($jewelrycrafting_total_xp)) {
            throw new InvalidArgumentException('non-nullable jewelrycrafting_total_xp cannot be null');
        }
        $this->container['jewelrycrafting_total_xp'] = $jewelrycrafting_total_xp;

        return $this;
    }

    /**
     * Gets cooking_level
     *
     * @return int
     */
    public function getCookingLevel(): int
    {
        return $this->container['cooking_level'];
    }

    /**
     * Sets cooking_level
     *
     * @param int $cooking_level Cooking level.
     *
     * @return $this
     */
    public function setCookingLevel(int $cooking_level): static
    {
        if (is_null($cooking_level)) {
            throw new InvalidArgumentException('non-nullable cooking_level cannot be null');
        }
        $this->container['cooking_level'] = $cooking_level;

        return $this;
    }

    /**
     * Gets cooking_total_xp
     *
     * @return int
     */
    public function getCookingTotalXp(): int
    {
        return $this->container['cooking_total_xp'];
    }

    /**
     * Sets cooking_total_xp
     *
     * @param int $cooking_total_xp Cooking total xp.
     *
     * @return $this
     */
    public function setCookingTotalXp(int $cooking_total_xp): static
    {
        if (is_null($cooking_total_xp)) {
            throw new InvalidArgumentException('non-nullable cooking_total_xp cannot be null');
        }
        $this->container['cooking_total_xp'] = $cooking_total_xp;

        return $this;
    }

    /**
     * Gets alchemy_level
     *
     * @return int
     */
    public function getAlchemyLevel(): int
    {
        return $this->container['alchemy_level'];
    }

    /**
     * Sets alchemy_level
     *
     * @param int $alchemy_level Alchemy level.
     *
     * @return $this
     */
    public function setAlchemyLevel(int $alchemy_level): static
    {
        if (is_null($alchemy_level)) {
            throw new InvalidArgumentException('non-nullable alchemy_level cannot be null');
        }
        $this->container['alchemy_level'] = $alchemy_level;

        return $this;
    }

    /**
     * Gets alchemy_total_xp
     *
     * @return int
     */
    public function getAlchemyTotalXp(): int
    {
        return $this->container['alchemy_total_xp'];
    }

    /**
     * Sets alchemy_total_xp
     *
     * @param int $alchemy_total_xp Alchemy total xp.
     *
     * @return $this
     */
    public function setAlchemyTotalXp(int $alchemy_total_xp): static
    {
        if (is_null($alchemy_total_xp)) {
            throw new InvalidArgumentException('non-nullable alchemy_total_xp cannot be null');
        }
        $this->container['alchemy_total_xp'] = $alchemy_total_xp;

        return $this;
    }

    /**
     * Gets gold
     *
     * @return int
     */
    public function getGold(): int
    {
        return $this->container['gold'];
    }

    /**
     * Sets gold
     *
     * @param int $gold The numbers of gold on this character.
     *
     * @return $this
     */
    public function setGold(int $gold): static
    {
        if (is_null($gold)) {
            throw new InvalidArgumentException('non-nullable gold cannot be null');
        }
        $this->container['gold'] = $gold;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


