<?php
/**
 * FakeCharacterSchema
 *
 * PHP version 8.1
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace \Kehet\ArtifactsMMO\\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use \Kehet\ArtifactsMMO\\ObjectSerializer;

/**
 * FakeCharacterSchema Class Doc Comment
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class FakeCharacterSchema implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'FakeCharacterSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'level' => 'int',
        'weapon_slot' => 'string',
        'rune_slot' => 'string',
        'shield_slot' => 'string',
        'helmet_slot' => 'string',
        'body_armor_slot' => 'string',
        'leg_armor_slot' => 'string',
        'boots_slot' => 'string',
        'ring1_slot' => 'string',
        'ring2_slot' => 'string',
        'amulet_slot' => 'string',
        'artifact1_slot' => 'string',
        'artifact2_slot' => 'string',
        'artifact3_slot' => 'string',
        'utility1_slot' => 'string',
        'utility1_slot_quantity' => 'int',
        'utility2_slot' => 'string',
        'utility2_slot_quantity' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'level' => null,
        'weapon_slot' => null,
        'rune_slot' => null,
        'shield_slot' => null,
        'helmet_slot' => null,
        'body_armor_slot' => null,
        'leg_armor_slot' => null,
        'boots_slot' => null,
        'ring1_slot' => null,
        'ring2_slot' => null,
        'amulet_slot' => null,
        'artifact1_slot' => null,
        'artifact2_slot' => null,
        'artifact3_slot' => null,
        'utility1_slot' => null,
        'utility1_slot_quantity' => null,
        'utility2_slot' => null,
        'utility2_slot_quantity' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'level' => false,
        'weapon_slot' => false,
        'rune_slot' => false,
        'shield_slot' => false,
        'helmet_slot' => false,
        'body_armor_slot' => false,
        'leg_armor_slot' => false,
        'boots_slot' => false,
        'ring1_slot' => false,
        'ring2_slot' => false,
        'amulet_slot' => false,
        'artifact1_slot' => false,
        'artifact2_slot' => false,
        'artifact3_slot' => false,
        'utility1_slot' => false,
        'utility1_slot_quantity' => false,
        'utility2_slot' => false,
        'utility2_slot_quantity' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'level' => 'level',
        'weapon_slot' => 'weapon_slot',
        'rune_slot' => 'rune_slot',
        'shield_slot' => 'shield_slot',
        'helmet_slot' => 'helmet_slot',
        'body_armor_slot' => 'body_armor_slot',
        'leg_armor_slot' => 'leg_armor_slot',
        'boots_slot' => 'boots_slot',
        'ring1_slot' => 'ring1_slot',
        'ring2_slot' => 'ring2_slot',
        'amulet_slot' => 'amulet_slot',
        'artifact1_slot' => 'artifact1_slot',
        'artifact2_slot' => 'artifact2_slot',
        'artifact3_slot' => 'artifact3_slot',
        'utility1_slot' => 'utility1_slot',
        'utility1_slot_quantity' => 'utility1_slot_quantity',
        'utility2_slot' => 'utility2_slot',
        'utility2_slot_quantity' => 'utility2_slot_quantity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'level' => 'setLevel',
        'weapon_slot' => 'setWeaponSlot',
        'rune_slot' => 'setRuneSlot',
        'shield_slot' => 'setShieldSlot',
        'helmet_slot' => 'setHelmetSlot',
        'body_armor_slot' => 'setBodyArmorSlot',
        'leg_armor_slot' => 'setLegArmorSlot',
        'boots_slot' => 'setBootsSlot',
        'ring1_slot' => 'setRing1Slot',
        'ring2_slot' => 'setRing2Slot',
        'amulet_slot' => 'setAmuletSlot',
        'artifact1_slot' => 'setArtifact1Slot',
        'artifact2_slot' => 'setArtifact2Slot',
        'artifact3_slot' => 'setArtifact3Slot',
        'utility1_slot' => 'setUtility1Slot',
        'utility1_slot_quantity' => 'setUtility1SlotQuantity',
        'utility2_slot' => 'setUtility2Slot',
        'utility2_slot_quantity' => 'setUtility2SlotQuantity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'level' => 'getLevel',
        'weapon_slot' => 'getWeaponSlot',
        'rune_slot' => 'getRuneSlot',
        'shield_slot' => 'getShieldSlot',
        'helmet_slot' => 'getHelmetSlot',
        'body_armor_slot' => 'getBodyArmorSlot',
        'leg_armor_slot' => 'getLegArmorSlot',
        'boots_slot' => 'getBootsSlot',
        'ring1_slot' => 'getRing1Slot',
        'ring2_slot' => 'getRing2Slot',
        'amulet_slot' => 'getAmuletSlot',
        'artifact1_slot' => 'getArtifact1Slot',
        'artifact2_slot' => 'getArtifact2Slot',
        'artifact3_slot' => 'getArtifact3Slot',
        'utility1_slot' => 'getUtility1Slot',
        'utility1_slot_quantity' => 'getUtility1SlotQuantity',
        'utility2_slot' => 'getUtility2Slot',
        'utility2_slot_quantity' => 'getUtility2SlotQuantity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('level', $data ?? [], null);
        $this->setIfExists('weapon_slot', $data ?? [], null);
        $this->setIfExists('rune_slot', $data ?? [], null);
        $this->setIfExists('shield_slot', $data ?? [], null);
        $this->setIfExists('helmet_slot', $data ?? [], null);
        $this->setIfExists('body_armor_slot', $data ?? [], null);
        $this->setIfExists('leg_armor_slot', $data ?? [], null);
        $this->setIfExists('boots_slot', $data ?? [], null);
        $this->setIfExists('ring1_slot', $data ?? [], null);
        $this->setIfExists('ring2_slot', $data ?? [], null);
        $this->setIfExists('amulet_slot', $data ?? [], null);
        $this->setIfExists('artifact1_slot', $data ?? [], null);
        $this->setIfExists('artifact2_slot', $data ?? [], null);
        $this->setIfExists('artifact3_slot', $data ?? [], null);
        $this->setIfExists('utility1_slot', $data ?? [], null);
        $this->setIfExists('utility1_slot_quantity', $data ?? [], 1);
        $this->setIfExists('utility2_slot', $data ?? [], null);
        $this->setIfExists('utility2_slot_quantity', $data ?? [], 1);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['level'] === null) {
            $invalidProperties[] = "'level' can't be null";
        }
        if (($this->container['level'] > 50)) {
            $invalidProperties[] = "invalid value for 'level', must be smaller than or equal to 50.";
        }

        if (($this->container['level'] < 1)) {
            $invalidProperties[] = "invalid value for 'level', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['utility1_slot_quantity']) && ($this->container['utility1_slot_quantity'] > 100)) {
            $invalidProperties[] = "invalid value for 'utility1_slot_quantity', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['utility1_slot_quantity']) && ($this->container['utility1_slot_quantity'] < 1)) {
            $invalidProperties[] = "invalid value for 'utility1_slot_quantity', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['utility2_slot_quantity']) && ($this->container['utility2_slot_quantity'] > 100)) {
            $invalidProperties[] = "invalid value for 'utility2_slot_quantity', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['utility2_slot_quantity']) && ($this->container['utility2_slot_quantity'] < 1)) {
            $invalidProperties[] = "invalid value for 'utility2_slot_quantity', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets level
     *
     * @return int
     */
    public function getLevel(): int
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param int $level Character level.
     *
     * @return $this
     */
    public function setLevel(int $level): static
    {
        if (is_null($level)) {
            throw new InvalidArgumentException('non-nullable level cannot be null');
        }

        if (($level > 50)) {
            throw new InvalidArgumentException('invalid value for $level when calling FakeCharacterSchema., must be smaller than or equal to 50.');
        }
        if (($level < 1)) {
            throw new InvalidArgumentException('invalid value for $level when calling FakeCharacterSchema., must be bigger than or equal to 1.');
        }

        $this->container['level'] = $level;

        return $this;
    }

    /**
     * Gets weapon_slot
     *
     * @return string|null
     */
    public function getWeaponSlot(): ?string
    {
        return $this->container['weapon_slot'];
    }

    /**
     * Sets weapon_slot
     *
     * @param string|null $weapon_slot Weapon slot item code.
     *
     * @return $this
     */
    public function setWeaponSlot(?string $weapon_slot): static
    {
        if (is_null($weapon_slot)) {
            throw new InvalidArgumentException('non-nullable weapon_slot cannot be null');
        }
        $this->container['weapon_slot'] = $weapon_slot;

        return $this;
    }

    /**
     * Gets rune_slot
     *
     * @return string|null
     */
    public function getRuneSlot(): ?string
    {
        return $this->container['rune_slot'];
    }

    /**
     * Sets rune_slot
     *
     * @param string|null $rune_slot Rune slot item code.
     *
     * @return $this
     */
    public function setRuneSlot(?string $rune_slot): static
    {
        if (is_null($rune_slot)) {
            throw new InvalidArgumentException('non-nullable rune_slot cannot be null');
        }
        $this->container['rune_slot'] = $rune_slot;

        return $this;
    }

    /**
     * Gets shield_slot
     *
     * @return string|null
     */
    public function getShieldSlot(): ?string
    {
        return $this->container['shield_slot'];
    }

    /**
     * Sets shield_slot
     *
     * @param string|null $shield_slot Shield slot item code.
     *
     * @return $this
     */
    public function setShieldSlot(?string $shield_slot): static
    {
        if (is_null($shield_slot)) {
            throw new InvalidArgumentException('non-nullable shield_slot cannot be null');
        }
        $this->container['shield_slot'] = $shield_slot;

        return $this;
    }

    /**
     * Gets helmet_slot
     *
     * @return string|null
     */
    public function getHelmetSlot(): ?string
    {
        return $this->container['helmet_slot'];
    }

    /**
     * Sets helmet_slot
     *
     * @param string|null $helmet_slot Helmet slot item code.
     *
     * @return $this
     */
    public function setHelmetSlot(?string $helmet_slot): static
    {
        if (is_null($helmet_slot)) {
            throw new InvalidArgumentException('non-nullable helmet_slot cannot be null');
        }
        $this->container['helmet_slot'] = $helmet_slot;

        return $this;
    }

    /**
     * Gets body_armor_slot
     *
     * @return string|null
     */
    public function getBodyArmorSlot(): ?string
    {
        return $this->container['body_armor_slot'];
    }

    /**
     * Sets body_armor_slot
     *
     * @param string|null $body_armor_slot Body armor slot item code.
     *
     * @return $this
     */
    public function setBodyArmorSlot(?string $body_armor_slot): static
    {
        if (is_null($body_armor_slot)) {
            throw new InvalidArgumentException('non-nullable body_armor_slot cannot be null');
        }
        $this->container['body_armor_slot'] = $body_armor_slot;

        return $this;
    }

    /**
     * Gets leg_armor_slot
     *
     * @return string|null
     */
    public function getLegArmorSlot(): ?string
    {
        return $this->container['leg_armor_slot'];
    }

    /**
     * Sets leg_armor_slot
     *
     * @param string|null $leg_armor_slot Leg armor slot item code.
     *
     * @return $this
     */
    public function setLegArmorSlot(?string $leg_armor_slot): static
    {
        if (is_null($leg_armor_slot)) {
            throw new InvalidArgumentException('non-nullable leg_armor_slot cannot be null');
        }
        $this->container['leg_armor_slot'] = $leg_armor_slot;

        return $this;
    }

    /**
     * Gets boots_slot
     *
     * @return string|null
     */
    public function getBootsSlot(): ?string
    {
        return $this->container['boots_slot'];
    }

    /**
     * Sets boots_slot
     *
     * @param string|null $boots_slot Boots slot item code.
     *
     * @return $this
     */
    public function setBootsSlot(?string $boots_slot): static
    {
        if (is_null($boots_slot)) {
            throw new InvalidArgumentException('non-nullable boots_slot cannot be null');
        }
        $this->container['boots_slot'] = $boots_slot;

        return $this;
    }

    /**
     * Gets ring1_slot
     *
     * @return string|null
     */
    public function getRing1Slot(): ?string
    {
        return $this->container['ring1_slot'];
    }

    /**
     * Sets ring1_slot
     *
     * @param string|null $ring1_slot Ring 1 slot item code.
     *
     * @return $this
     */
    public function setRing1Slot(?string $ring1_slot): static
    {
        if (is_null($ring1_slot)) {
            throw new InvalidArgumentException('non-nullable ring1_slot cannot be null');
        }
        $this->container['ring1_slot'] = $ring1_slot;

        return $this;
    }

    /**
     * Gets ring2_slot
     *
     * @return string|null
     */
    public function getRing2Slot(): ?string
    {
        return $this->container['ring2_slot'];
    }

    /**
     * Sets ring2_slot
     *
     * @param string|null $ring2_slot Ring 2 slot item code.
     *
     * @return $this
     */
    public function setRing2Slot(?string $ring2_slot): static
    {
        if (is_null($ring2_slot)) {
            throw new InvalidArgumentException('non-nullable ring2_slot cannot be null');
        }
        $this->container['ring2_slot'] = $ring2_slot;

        return $this;
    }

    /**
     * Gets amulet_slot
     *
     * @return string|null
     */
    public function getAmuletSlot(): ?string
    {
        return $this->container['amulet_slot'];
    }

    /**
     * Sets amulet_slot
     *
     * @param string|null $amulet_slot Amulet slot item code.
     *
     * @return $this
     */
    public function setAmuletSlot(?string $amulet_slot): static
    {
        if (is_null($amulet_slot)) {
            throw new InvalidArgumentException('non-nullable amulet_slot cannot be null');
        }
        $this->container['amulet_slot'] = $amulet_slot;

        return $this;
    }

    /**
     * Gets artifact1_slot
     *
     * @return string|null
     */
    public function getArtifact1Slot(): ?string
    {
        return $this->container['artifact1_slot'];
    }

    /**
     * Sets artifact1_slot
     *
     * @param string|null $artifact1_slot Artifact 1 slot item code.
     *
     * @return $this
     */
    public function setArtifact1Slot(?string $artifact1_slot): static
    {
        if (is_null($artifact1_slot)) {
            throw new InvalidArgumentException('non-nullable artifact1_slot cannot be null');
        }
        $this->container['artifact1_slot'] = $artifact1_slot;

        return $this;
    }

    /**
     * Gets artifact2_slot
     *
     * @return string|null
     */
    public function getArtifact2Slot(): ?string
    {
        return $this->container['artifact2_slot'];
    }

    /**
     * Sets artifact2_slot
     *
     * @param string|null $artifact2_slot Artifact 2 slot item code.
     *
     * @return $this
     */
    public function setArtifact2Slot(?string $artifact2_slot): static
    {
        if (is_null($artifact2_slot)) {
            throw new InvalidArgumentException('non-nullable artifact2_slot cannot be null');
        }
        $this->container['artifact2_slot'] = $artifact2_slot;

        return $this;
    }

    /**
     * Gets artifact3_slot
     *
     * @return string|null
     */
    public function getArtifact3Slot(): ?string
    {
        return $this->container['artifact3_slot'];
    }

    /**
     * Sets artifact3_slot
     *
     * @param string|null $artifact3_slot Artifact 3 slot item code.
     *
     * @return $this
     */
    public function setArtifact3Slot(?string $artifact3_slot): static
    {
        if (is_null($artifact3_slot)) {
            throw new InvalidArgumentException('non-nullable artifact3_slot cannot be null');
        }
        $this->container['artifact3_slot'] = $artifact3_slot;

        return $this;
    }

    /**
     * Gets utility1_slot
     *
     * @return string|null
     */
    public function getUtility1Slot(): ?string
    {
        return $this->container['utility1_slot'];
    }

    /**
     * Sets utility1_slot
     *
     * @param string|null $utility1_slot Utility 1 slot item code.
     *
     * @return $this
     */
    public function setUtility1Slot(?string $utility1_slot): static
    {
        if (is_null($utility1_slot)) {
            throw new InvalidArgumentException('non-nullable utility1_slot cannot be null');
        }
        $this->container['utility1_slot'] = $utility1_slot;

        return $this;
    }

    /**
     * Gets utility1_slot_quantity
     *
     * @return int|null
     */
    public function getUtility1SlotQuantity(): ?int
    {
        return $this->container['utility1_slot_quantity'];
    }

    /**
     * Sets utility1_slot_quantity
     *
     * @param int|null $utility1_slot_quantity Utility 1 quantity.
     *
     * @return $this
     */
    public function setUtility1SlotQuantity(?int $utility1_slot_quantity): static
    {
        if (is_null($utility1_slot_quantity)) {
            throw new InvalidArgumentException('non-nullable utility1_slot_quantity cannot be null');
        }

        if (($utility1_slot_quantity > 100)) {
            throw new InvalidArgumentException('invalid value for $utility1_slot_quantity when calling FakeCharacterSchema., must be smaller than or equal to 100.');
        }
        if (($utility1_slot_quantity < 1)) {
            throw new InvalidArgumentException('invalid value for $utility1_slot_quantity when calling FakeCharacterSchema., must be bigger than or equal to 1.');
        }

        $this->container['utility1_slot_quantity'] = $utility1_slot_quantity;

        return $this;
    }

    /**
     * Gets utility2_slot
     *
     * @return string|null
     */
    public function getUtility2Slot(): ?string
    {
        return $this->container['utility2_slot'];
    }

    /**
     * Sets utility2_slot
     *
     * @param string|null $utility2_slot Utility 2 slot item code.
     *
     * @return $this
     */
    public function setUtility2Slot(?string $utility2_slot): static
    {
        if (is_null($utility2_slot)) {
            throw new InvalidArgumentException('non-nullable utility2_slot cannot be null');
        }
        $this->container['utility2_slot'] = $utility2_slot;

        return $this;
    }

    /**
     * Gets utility2_slot_quantity
     *
     * @return int|null
     */
    public function getUtility2SlotQuantity(): ?int
    {
        return $this->container['utility2_slot_quantity'];
    }

    /**
     * Sets utility2_slot_quantity
     *
     * @param int|null $utility2_slot_quantity Utility 2 quantity.
     *
     * @return $this
     */
    public function setUtility2SlotQuantity(?int $utility2_slot_quantity): static
    {
        if (is_null($utility2_slot_quantity)) {
            throw new InvalidArgumentException('non-nullable utility2_slot_quantity cannot be null');
        }

        if (($utility2_slot_quantity > 100)) {
            throw new InvalidArgumentException('invalid value for $utility2_slot_quantity when calling FakeCharacterSchema., must be smaller than or equal to 100.');
        }
        if (($utility2_slot_quantity < 1)) {
            throw new InvalidArgumentException('invalid value for $utility2_slot_quantity when calling FakeCharacterSchema., must be bigger than or equal to 1.');
        }

        $this->container['utility2_slot_quantity'] = $utility2_slot_quantity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


