<?php
/**
 * StatusSchema
 *
 * PHP version 8.1
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace \Kehet\ArtifactsMMO\\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use \Kehet\ArtifactsMMO\\ObjectSerializer;

/**
 * StatusSchema Class Doc Comment
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class StatusSchema implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'StatusSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'version' => 'string',
        'server_time' => '\DateTime',
        'max_level' => 'int',
        'max_skill_level' => 'int',
        'characters_online' => 'int',
        'season' => '\\Kehet\ArtifactsMMO\\Model\SeasonSchema',
        'rate_limits' => '\\Kehet\ArtifactsMMO\\Model\RateLimitSchema[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'version' => null,
        'server_time' => 'date-time',
        'max_level' => null,
        'max_skill_level' => null,
        'characters_online' => null,
        'season' => null,
        'rate_limits' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'version' => false,
        'server_time' => false,
        'max_level' => false,
        'max_skill_level' => false,
        'characters_online' => false,
        'season' => false,
        'rate_limits' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'version' => 'version',
        'server_time' => 'server_time',
        'max_level' => 'max_level',
        'max_skill_level' => 'max_skill_level',
        'characters_online' => 'characters_online',
        'season' => 'season',
        'rate_limits' => 'rate_limits'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'version' => 'setVersion',
        'server_time' => 'setServerTime',
        'max_level' => 'setMaxLevel',
        'max_skill_level' => 'setMaxSkillLevel',
        'characters_online' => 'setCharactersOnline',
        'season' => 'setSeason',
        'rate_limits' => 'setRateLimits'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'version' => 'getVersion',
        'server_time' => 'getServerTime',
        'max_level' => 'getMaxLevel',
        'max_skill_level' => 'getMaxSkillLevel',
        'characters_online' => 'getCharactersOnline',
        'season' => 'getSeason',
        'rate_limits' => 'getRateLimits'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('server_time', $data ?? [], null);
        $this->setIfExists('max_level', $data ?? [], null);
        $this->setIfExists('max_skill_level', $data ?? [], null);
        $this->setIfExists('characters_online', $data ?? [], null);
        $this->setIfExists('season', $data ?? [], null);
        $this->setIfExists('rate_limits', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['version'] === null) {
            $invalidProperties[] = "'version' can't be null";
        }
        if ($this->container['server_time'] === null) {
            $invalidProperties[] = "'server_time' can't be null";
        }
        if ($this->container['max_level'] === null) {
            $invalidProperties[] = "'max_level' can't be null";
        }
        if ($this->container['max_skill_level'] === null) {
            $invalidProperties[] = "'max_skill_level' can't be null";
        }
        if ($this->container['characters_online'] === null) {
            $invalidProperties[] = "'characters_online' can't be null";
        }
        if ($this->container['rate_limits'] === null) {
            $invalidProperties[] = "'rate_limits' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets version
     *
     * @return string
     */
    public function getVersion(): string
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string $version Game version.
     *
     * @return $this
     */
    public function setVersion(string $version): static
    {
        if (is_null($version)) {
            throw new InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets server_time
     *
     * @return \DateTime
     */
    public function getServerTime(): \DateTime
    {
        return $this->container['server_time'];
    }

    /**
     * Sets server_time
     *
     * @param \DateTime $server_time Server time.
     *
     * @return $this
     */
    public function setServerTime(\DateTime $server_time): static
    {
        if (is_null($server_time)) {
            throw new InvalidArgumentException('non-nullable server_time cannot be null');
        }
        $this->container['server_time'] = $server_time;

        return $this;
    }

    /**
     * Gets max_level
     *
     * @return int
     */
    public function getMaxLevel(): int
    {
        return $this->container['max_level'];
    }

    /**
     * Sets max_level
     *
     * @param int $max_level Maximum level.
     *
     * @return $this
     */
    public function setMaxLevel(int $max_level): static
    {
        if (is_null($max_level)) {
            throw new InvalidArgumentException('non-nullable max_level cannot be null');
        }
        $this->container['max_level'] = $max_level;

        return $this;
    }

    /**
     * Gets max_skill_level
     *
     * @return int
     */
    public function getMaxSkillLevel(): int
    {
        return $this->container['max_skill_level'];
    }

    /**
     * Sets max_skill_level
     *
     * @param int $max_skill_level Maximum skill level.
     *
     * @return $this
     */
    public function setMaxSkillLevel(int $max_skill_level): static
    {
        if (is_null($max_skill_level)) {
            throw new InvalidArgumentException('non-nullable max_skill_level cannot be null');
        }
        $this->container['max_skill_level'] = $max_skill_level;

        return $this;
    }

    /**
     * Gets characters_online
     *
     * @return int
     */
    public function getCharactersOnline(): int
    {
        return $this->container['characters_online'];
    }

    /**
     * Sets characters_online
     *
     * @param int $characters_online Characters online.
     *
     * @return $this
     */
    public function setCharactersOnline(int $characters_online): static
    {
        if (is_null($characters_online)) {
            throw new InvalidArgumentException('non-nullable characters_online cannot be null');
        }
        $this->container['characters_online'] = $characters_online;

        return $this;
    }

    /**
     * Gets season
     *
     * @return \\Kehet\ArtifactsMMO\\Model\SeasonSchema|null
     */
    public function getSeason(): ?\\Kehet\ArtifactsMMO\\Model\SeasonSchema
    {
        return $this->container['season'];
    }

    /**
     * Sets season
     *
     * @param \\Kehet\ArtifactsMMO\\Model\SeasonSchema|null $season Current season details.
     *
     * @return $this
     */
    public function setSeason(?\\Kehet\ArtifactsMMO\\Model\SeasonSchema $season): static
    {
        if (is_null($season)) {
            throw new InvalidArgumentException('non-nullable season cannot be null');
        }
        $this->container['season'] = $season;

        return $this;
    }

    /**
     * Gets rate_limits
     *
     * @return \\Kehet\ArtifactsMMO\\Model\RateLimitSchema[]
     */
    public function getRateLimits(): array
    {
        return $this->container['rate_limits'];
    }

    /**
     * Sets rate_limits
     *
     * @param \\Kehet\ArtifactsMMO\\Model\RateLimitSchema[] $rate_limits Rate limits.
     *
     * @return $this
     */
    public function setRateLimits(array $rate_limits): static
    {
        if (is_null($rate_limits)) {
            throw new InvalidArgumentException('non-nullable rate_limits cannot be null');
        }
        $this->container['rate_limits'] = $rate_limits;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


