<?php

/**
 * CharactersApi
 * PHP version 8.1
 *
 * @package  Kehet\ArtifactsMMO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kehet\ArtifactsMMO\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Kehet\ArtifactsMMO\ApiException;
use Kehet\ArtifactsMMO\Configuration;
use Kehet\ArtifactsMMO\HeaderSelector;
use Kehet\ArtifactsMMO\FormDataProcessor;
use Kehet\ArtifactsMMO\ObjectSerializer;

/**
 * CharactersApi Class Doc Comment
 *
 * @package  Kehet\ArtifactsMMO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CharactersApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createCharacterCharactersCreatePost' => [
            'application/json',
        ],
        'deleteCharacterCharactersDeletePost' => [
            'application/json',
        ],
        'getActiveCharactersCharactersActiveGet' => [
            'application/json',
        ],
        'getCharacterCharactersNameGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation createCharacterCharactersCreatePost
     *
     * Create Character
     *
     * @param  \Kehet\ArtifactsMMO\Model\AddCharacterSchema $add_character_schema add_character_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createCharacterCharactersCreatePost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Kehet\ArtifactsMMO\Model\CharacterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema
     */
    public function createCharacterCharactersCreatePost(
        \Kehet\ArtifactsMMO\Model\AddCharacterSchema $add_character_schema,
        string $contentType = self::contentTypes['createCharacterCharactersCreatePost'][0]
    ): \Kehet\ArtifactsMMO\Model\CharacterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema {
        list($response) = $this->createCharacterCharactersCreatePostWithHttpInfo($add_character_schema, $contentType);
        return $response;
    }

    /**
     * Operation createCharacterCharactersCreatePostWithHttpInfo
     *
     * Create Character
     *
     * @param  \Kehet\ArtifactsMMO\Model\AddCharacterSchema $add_character_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createCharacterCharactersCreatePost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Kehet\ArtifactsMMO\Model\CharacterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function createCharacterCharactersCreatePostWithHttpInfo(
        \Kehet\ArtifactsMMO\Model\AddCharacterSchema $add_character_schema,
        string $contentType = self::contentTypes['createCharacterCharactersCreatePost'][0]
    ): array {
        $request = $this->createCharacterCharactersCreatePostRequest($add_character_schema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema',
                        $request,
                        $response,
                    );
                case 494:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 495:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 550:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 494:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 495:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 550:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation createCharacterCharactersCreatePostAsync
     *
     * Create Character
     *
     * @param  \Kehet\ArtifactsMMO\Model\AddCharacterSchema $add_character_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createCharacterCharactersCreatePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createCharacterCharactersCreatePostAsync(
        \Kehet\ArtifactsMMO\Model\AddCharacterSchema $add_character_schema,
        string $contentType = self::contentTypes['createCharacterCharactersCreatePost'][0]
    ): PromiseInterface {
        return $this->createCharacterCharactersCreatePostAsyncWithHttpInfo($add_character_schema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createCharacterCharactersCreatePostAsyncWithHttpInfo
     *
     * Create Character
     *
     * @param  \Kehet\ArtifactsMMO\Model\AddCharacterSchema $add_character_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createCharacterCharactersCreatePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createCharacterCharactersCreatePostAsyncWithHttpInfo(
        \Kehet\ArtifactsMMO\Model\AddCharacterSchema $add_character_schema,
        string $contentType = self::contentTypes['createCharacterCharactersCreatePost'][0]
    ): PromiseInterface {
        $returnType = '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema';
        $request = $this->createCharacterCharactersCreatePostRequest($add_character_schema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createCharacterCharactersCreatePost'
     *
     * @param  \Kehet\ArtifactsMMO\Model\AddCharacterSchema $add_character_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createCharacterCharactersCreatePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createCharacterCharactersCreatePostRequest(
        \Kehet\ArtifactsMMO\Model\AddCharacterSchema $add_character_schema,
        string $contentType = self::contentTypes['createCharacterCharactersCreatePost'][0]
    ): Request {

        // verify the required parameter 'add_character_schema' is set
        if ($add_character_schema === null || (is_array($add_character_schema) && count($add_character_schema) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $add_character_schema when calling createCharacterCharactersCreatePost'
            );
        }


        $resourcePath = '/characters/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($add_character_schema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($add_character_schema));
            } else {
                $httpBody = $add_character_schema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteCharacterCharactersDeletePost
     *
     * Delete Character
     *
     * @param  \Kehet\ArtifactsMMO\Model\DeleteCharacterSchema $delete_character_schema delete_character_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteCharacterCharactersDeletePost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Kehet\ArtifactsMMO\Model\CharacterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema
     */
    public function deleteCharacterCharactersDeletePost(
        \Kehet\ArtifactsMMO\Model\DeleteCharacterSchema $delete_character_schema,
        string $contentType = self::contentTypes['deleteCharacterCharactersDeletePost'][0]
    ): \Kehet\ArtifactsMMO\Model\CharacterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema {
        list($response) = $this->deleteCharacterCharactersDeletePostWithHttpInfo($delete_character_schema, $contentType);
        return $response;
    }

    /**
     * Operation deleteCharacterCharactersDeletePostWithHttpInfo
     *
     * Delete Character
     *
     * @param  \Kehet\ArtifactsMMO\Model\DeleteCharacterSchema $delete_character_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteCharacterCharactersDeletePost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Kehet\ArtifactsMMO\Model\CharacterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteCharacterCharactersDeletePostWithHttpInfo(
        \Kehet\ArtifactsMMO\Model\DeleteCharacterSchema $delete_character_schema,
        string $contentType = self::contentTypes['deleteCharacterCharactersDeletePost'][0]
    ): array {
        $request = $this->deleteCharacterCharactersDeletePostRequest($delete_character_schema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema',
                        $request,
                        $response,
                    );
                case 498:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 498:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation deleteCharacterCharactersDeletePostAsync
     *
     * Delete Character
     *
     * @param  \Kehet\ArtifactsMMO\Model\DeleteCharacterSchema $delete_character_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteCharacterCharactersDeletePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function deleteCharacterCharactersDeletePostAsync(
        \Kehet\ArtifactsMMO\Model\DeleteCharacterSchema $delete_character_schema,
        string $contentType = self::contentTypes['deleteCharacterCharactersDeletePost'][0]
    ): PromiseInterface {
        return $this->deleteCharacterCharactersDeletePostAsyncWithHttpInfo($delete_character_schema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteCharacterCharactersDeletePostAsyncWithHttpInfo
     *
     * Delete Character
     *
     * @param  \Kehet\ArtifactsMMO\Model\DeleteCharacterSchema $delete_character_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteCharacterCharactersDeletePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function deleteCharacterCharactersDeletePostAsyncWithHttpInfo(
        \Kehet\ArtifactsMMO\Model\DeleteCharacterSchema $delete_character_schema,
        string $contentType = self::contentTypes['deleteCharacterCharactersDeletePost'][0]
    ): PromiseInterface {
        $returnType = '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema';
        $request = $this->deleteCharacterCharactersDeletePostRequest($delete_character_schema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteCharacterCharactersDeletePost'
     *
     * @param  \Kehet\ArtifactsMMO\Model\DeleteCharacterSchema $delete_character_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteCharacterCharactersDeletePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteCharacterCharactersDeletePostRequest(
        \Kehet\ArtifactsMMO\Model\DeleteCharacterSchema $delete_character_schema,
        string $contentType = self::contentTypes['deleteCharacterCharactersDeletePost'][0]
    ): Request {

        // verify the required parameter 'delete_character_schema' is set
        if ($delete_character_schema === null || (is_array($delete_character_schema) && count($delete_character_schema) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $delete_character_schema when calling deleteCharacterCharactersDeletePost'
            );
        }


        $resourcePath = '/characters/delete';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($delete_character_schema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($delete_character_schema));
            } else {
                $httpBody = $delete_character_schema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getActiveCharactersCharactersActiveGet
     *
     * Get Active Characters
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getActiveCharactersCharactersActiveGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Kehet\ArtifactsMMO\Model\DataPageActiveCharacterSchema
     */
    public function getActiveCharactersCharactersActiveGet(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getActiveCharactersCharactersActiveGet'][0]
    ): \Kehet\ArtifactsMMO\Model\DataPageActiveCharacterSchema {
        list($response) = $this->getActiveCharactersCharactersActiveGetWithHttpInfo($page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getActiveCharactersCharactersActiveGetWithHttpInfo
     *
     * Get Active Characters
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getActiveCharactersCharactersActiveGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Kehet\ArtifactsMMO\Model\DataPageActiveCharacterSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getActiveCharactersCharactersActiveGetWithHttpInfo(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getActiveCharactersCharactersActiveGet'][0]
    ): array {
        $request = $this->getActiveCharactersCharactersActiveGetRequest($page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\DataPageActiveCharacterSchema',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kehet\ArtifactsMMO\Model\DataPageActiveCharacterSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\DataPageActiveCharacterSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation getActiveCharactersCharactersActiveGetAsync
     *
     * Get Active Characters
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getActiveCharactersCharactersActiveGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getActiveCharactersCharactersActiveGetAsync(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getActiveCharactersCharactersActiveGet'][0]
    ): PromiseInterface {
        return $this->getActiveCharactersCharactersActiveGetAsyncWithHttpInfo($page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getActiveCharactersCharactersActiveGetAsyncWithHttpInfo
     *
     * Get Active Characters
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getActiveCharactersCharactersActiveGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getActiveCharactersCharactersActiveGetAsyncWithHttpInfo(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getActiveCharactersCharactersActiveGet'][0]
    ): PromiseInterface {
        $returnType = '\Kehet\ArtifactsMMO\Model\DataPageActiveCharacterSchema';
        $request = $this->getActiveCharactersCharactersActiveGetRequest($page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getActiveCharactersCharactersActiveGet'
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getActiveCharactersCharactersActiveGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getActiveCharactersCharactersActiveGetRequest(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getActiveCharactersCharactersActiveGet'][0]
    ): Request {

        if ($page !== null && $page < 1) {
            throw new InvalidArgumentException('invalid value for "$page" when calling CharactersApi.getActiveCharactersCharactersActiveGet, must be bigger than or equal to 1.');
        }

        if ($size !== null && $size > 100) {
            throw new InvalidArgumentException('invalid value for "$size" when calling CharactersApi.getActiveCharactersCharactersActiveGet, must be smaller than or equal to 100.');
        }
        if ($size !== null && $size < 1) {
            throw new InvalidArgumentException('invalid value for "$size" when calling CharactersApi.getActiveCharactersCharactersActiveGet, must be bigger than or equal to 1.');
        }


        $resourcePath = '/characters/active';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCharacterCharactersNameGet
     *
     * Get Character
     *
     * @param  string $name The name of the character. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCharacterCharactersNameGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Kehet\ArtifactsMMO\Model\CharacterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema
     */
    public function getCharacterCharactersNameGet(
        string $name,
        string $contentType = self::contentTypes['getCharacterCharactersNameGet'][0]
    ): \Kehet\ArtifactsMMO\Model\CharacterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema {
        list($response) = $this->getCharacterCharactersNameGetWithHttpInfo($name, $contentType);
        return $response;
    }

    /**
     * Operation getCharacterCharactersNameGetWithHttpInfo
     *
     * Get Character
     *
     * @param  string $name The name of the character. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCharacterCharactersNameGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Kehet\ArtifactsMMO\Model\CharacterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCharacterCharactersNameGetWithHttpInfo(
        string $name,
        string $contentType = self::contentTypes['getCharacterCharactersNameGet'][0]
    ): array {
        $request = $this->getCharacterCharactersNameGetRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation getCharacterCharactersNameGetAsync
     *
     * Get Character
     *
     * @param  string $name The name of the character. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCharacterCharactersNameGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getCharacterCharactersNameGetAsync(
        string $name,
        string $contentType = self::contentTypes['getCharacterCharactersNameGet'][0]
    ): PromiseInterface {
        return $this->getCharacterCharactersNameGetAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCharacterCharactersNameGetAsyncWithHttpInfo
     *
     * Get Character
     *
     * @param  string $name The name of the character. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCharacterCharactersNameGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getCharacterCharactersNameGetAsyncWithHttpInfo(
        string $name,
        string $contentType = self::contentTypes['getCharacterCharactersNameGet'][0]
    ): PromiseInterface {
        $returnType = '\Kehet\ArtifactsMMO\Model\CharacterResponseSchema';
        $request = $this->getCharacterCharactersNameGetRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCharacterCharactersNameGet'
     *
     * @param  string $name The name of the character. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCharacterCharactersNameGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCharacterCharactersNameGetRequest(
        string $name,
        string $contentType = self::contentTypes['getCharacterCharactersNameGet'][0]
    ): Request {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $name when calling getCharacterCharactersNameGet'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_-]+$/", $name)) {
            throw new InvalidArgumentException("invalid value for \"name\" when calling CharactersApi.getCharacterCharactersNameGet, must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }


        $resourcePath = '/characters/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
