<?php
/**
 * EffectsApi
 * PHP version 8.1
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace \Kehet\ArtifactsMMO\\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use \Kehet\ArtifactsMMO\\ApiException;
use \Kehet\ArtifactsMMO\\Configuration;
use \Kehet\ArtifactsMMO\\HeaderSelector;
use \Kehet\ArtifactsMMO\\FormDataProcessor;
use \Kehet\ArtifactsMMO\\ObjectSerializer;

/**
 * EffectsApi Class Doc Comment
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EffectsApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAllEffectsEffectsGet' => [
            'application/json',
        ],
        'getEffectEffectsCodeGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation getAllEffectsEffectsGet
     *
     * Get All Effects
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllEffectsEffectsGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \\Kehet\ArtifactsMMO\\Model\DataPageEffectSchema
     */
    public function getAllEffectsEffectsGet(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllEffectsEffectsGet'][0]
    ): \\Kehet\ArtifactsMMO\\Model\DataPageEffectSchema
    {
        list($response) = $this->getAllEffectsEffectsGetWithHttpInfo($page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getAllEffectsEffectsGetWithHttpInfo
     *
     * Get All Effects
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllEffectsEffectsGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \\Kehet\ArtifactsMMO\\Model\DataPageEffectSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllEffectsEffectsGetWithHttpInfo(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllEffectsEffectsGet'][0]
    ): array
    {
        $request = $this->getAllEffectsEffectsGetRequest($page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\\Kehet\ArtifactsMMO\\Model\DataPageEffectSchema',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\\Kehet\ArtifactsMMO\\Model\DataPageEffectSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\\Kehet\ArtifactsMMO\\Model\DataPageEffectSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation getAllEffectsEffectsGetAsync
     *
     * Get All Effects
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllEffectsEffectsGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getAllEffectsEffectsGetAsync(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllEffectsEffectsGet'][0]
    ): PromiseInterface
    {
        return $this->getAllEffectsEffectsGetAsyncWithHttpInfo($page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllEffectsEffectsGetAsyncWithHttpInfo
     *
     * Get All Effects
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllEffectsEffectsGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getAllEffectsEffectsGetAsyncWithHttpInfo(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllEffectsEffectsGet'][0]
    ): PromiseInterface
    {
        $returnType = '\\Kehet\ArtifactsMMO\\Model\DataPageEffectSchema';
        $request = $this->getAllEffectsEffectsGetRequest($page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllEffectsEffectsGet'
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllEffectsEffectsGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllEffectsEffectsGetRequest(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllEffectsEffectsGet'][0]
    ): Request
    {

        if ($page !== null && $page < 1) {
            throw new InvalidArgumentException('invalid value for "$page" when calling EffectsApi.getAllEffectsEffectsGet, must be bigger than or equal to 1.');
        }
        
        if ($size !== null && $size > 100) {
            throw new InvalidArgumentException('invalid value for "$size" when calling EffectsApi.getAllEffectsEffectsGet, must be smaller than or equal to 100.');
        }
        if ($size !== null && $size < 1) {
            throw new InvalidArgumentException('invalid value for "$size" when calling EffectsApi.getAllEffectsEffectsGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/effects';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getEffectEffectsCodeGet
     *
     * Get Effect
     *
     * @param  string $code The code of the effect. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEffectEffectsCodeGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \\Kehet\ArtifactsMMO\\Model\EffectResponseSchema|\\Kehet\ArtifactsMMO\\Model\ErrorResponseSchema
     */
    public function getEffectEffectsCodeGet(
        string $code,
        string $contentType = self::contentTypes['getEffectEffectsCodeGet'][0]
    ): \\Kehet\ArtifactsMMO\\Model\EffectResponseSchema|\\Kehet\ArtifactsMMO\\Model\ErrorResponseSchema
    {
        list($response) = $this->getEffectEffectsCodeGetWithHttpInfo($code, $contentType);
        return $response;
    }

    /**
     * Operation getEffectEffectsCodeGetWithHttpInfo
     *
     * Get Effect
     *
     * @param  string $code The code of the effect. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEffectEffectsCodeGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \\Kehet\ArtifactsMMO\\Model\EffectResponseSchema|\\Kehet\ArtifactsMMO\\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEffectEffectsCodeGetWithHttpInfo(
        string $code,
        string $contentType = self::contentTypes['getEffectEffectsCodeGet'][0]
    ): array
    {
        $request = $this->getEffectEffectsCodeGetRequest($code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\\Kehet\ArtifactsMMO\\Model\EffectResponseSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\\Kehet\ArtifactsMMO\\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\\Kehet\ArtifactsMMO\\Model\EffectResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\\Kehet\ArtifactsMMO\\Model\EffectResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\\Kehet\ArtifactsMMO\\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation getEffectEffectsCodeGetAsync
     *
     * Get Effect
     *
     * @param  string $code The code of the effect. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEffectEffectsCodeGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getEffectEffectsCodeGetAsync(
        string $code,
        string $contentType = self::contentTypes['getEffectEffectsCodeGet'][0]
    ): PromiseInterface
    {
        return $this->getEffectEffectsCodeGetAsyncWithHttpInfo($code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEffectEffectsCodeGetAsyncWithHttpInfo
     *
     * Get Effect
     *
     * @param  string $code The code of the effect. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEffectEffectsCodeGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getEffectEffectsCodeGetAsyncWithHttpInfo(
        string $code,
        string $contentType = self::contentTypes['getEffectEffectsCodeGet'][0]
    ): PromiseInterface
    {
        $returnType = '\\Kehet\ArtifactsMMO\\Model\EffectResponseSchema';
        $request = $this->getEffectEffectsCodeGetRequest($code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEffectEffectsCodeGet'
     *
     * @param  string $code The code of the effect. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEffectEffectsCodeGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getEffectEffectsCodeGetRequest(
        string $code,
        string $contentType = self::contentTypes['getEffectEffectsCodeGet'][0]
    ): Request
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $code when calling getEffectEffectsCodeGet'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_-]+$/", $code)) {
            throw new InvalidArgumentException("invalid value for \"code\" when calling EffectsApi.getEffectEffectsCodeGet, must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }
        

        $resourcePath = '/effects/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
