<?php

/**
 * EventsApi
 * PHP version 8.1
 *
 * @package  Kehet\ArtifactsMMO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kehet\ArtifactsMMO\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Kehet\ArtifactsMMO\ApiException;
use Kehet\ArtifactsMMO\Configuration;
use Kehet\ArtifactsMMO\HeaderSelector;
use Kehet\ArtifactsMMO\FormDataProcessor;
use Kehet\ArtifactsMMO\ObjectSerializer;

/**
 * EventsApi Class Doc Comment
 *
 * @package  Kehet\ArtifactsMMO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventsApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAllActiveEventsEventsActiveGet' => [
            'application/json',
        ],
        'getAllEventsEventsGet' => [
            'application/json',
        ],
        'spawnEventEventsSpawnPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation getAllActiveEventsEventsActiveGet
     *
     * Get All Active Events
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllActiveEventsEventsActiveGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Kehet\ArtifactsMMO\Model\DataPageActiveEventSchema
     */
    public function getAllActiveEventsEventsActiveGet(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllActiveEventsEventsActiveGet'][0]
    ): \Kehet\ArtifactsMMO\Model\DataPageActiveEventSchema {
        list($response) = $this->getAllActiveEventsEventsActiveGetWithHttpInfo($page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getAllActiveEventsEventsActiveGetWithHttpInfo
     *
     * Get All Active Events
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllActiveEventsEventsActiveGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Kehet\ArtifactsMMO\Model\DataPageActiveEventSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllActiveEventsEventsActiveGetWithHttpInfo(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllActiveEventsEventsActiveGet'][0]
    ): array {
        $request = $this->getAllActiveEventsEventsActiveGetRequest($page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\DataPageActiveEventSchema',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kehet\ArtifactsMMO\Model\DataPageActiveEventSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\DataPageActiveEventSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation getAllActiveEventsEventsActiveGetAsync
     *
     * Get All Active Events
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllActiveEventsEventsActiveGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getAllActiveEventsEventsActiveGetAsync(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllActiveEventsEventsActiveGet'][0]
    ): PromiseInterface {
        return $this->getAllActiveEventsEventsActiveGetAsyncWithHttpInfo($page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllActiveEventsEventsActiveGetAsyncWithHttpInfo
     *
     * Get All Active Events
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllActiveEventsEventsActiveGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getAllActiveEventsEventsActiveGetAsyncWithHttpInfo(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllActiveEventsEventsActiveGet'][0]
    ): PromiseInterface {
        $returnType = '\Kehet\ArtifactsMMO\Model\DataPageActiveEventSchema';
        $request = $this->getAllActiveEventsEventsActiveGetRequest($page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllActiveEventsEventsActiveGet'
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllActiveEventsEventsActiveGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllActiveEventsEventsActiveGetRequest(
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllActiveEventsEventsActiveGet'][0]
    ): Request {

        if ($page !== null && $page < 1) {
            throw new InvalidArgumentException('invalid value for "$page" when calling EventsApi.getAllActiveEventsEventsActiveGet, must be bigger than or equal to 1.');
        }

        if ($size !== null && $size > 100) {
            throw new InvalidArgumentException('invalid value for "$size" when calling EventsApi.getAllActiveEventsEventsActiveGet, must be smaller than or equal to 100.');
        }
        if ($size !== null && $size < 1) {
            throw new InvalidArgumentException('invalid value for "$size" when calling EventsApi.getAllActiveEventsEventsActiveGet, must be bigger than or equal to 1.');
        }


        $resourcePath = '/events/active';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllEventsEventsGet
     *
     * Get All Events
     *
     * @param  \KehetArtifactsMMOModelMapContentType|null $type Type of events. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllEventsEventsGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Kehet\ArtifactsMMO\Model\DataPageEventSchema
     */
    public function getAllEventsEventsGet(
        ?\KehetArtifactsMMOModelMapContentType $type = null,
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllEventsEventsGet'][0]
    ): \Kehet\ArtifactsMMO\Model\DataPageEventSchema {
        list($response) = $this->getAllEventsEventsGetWithHttpInfo($type, $page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getAllEventsEventsGetWithHttpInfo
     *
     * Get All Events
     *
     * @param  \KehetArtifactsMMOModelMapContentType|null $type Type of events. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllEventsEventsGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Kehet\ArtifactsMMO\Model\DataPageEventSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllEventsEventsGetWithHttpInfo(
        ?\KehetArtifactsMMOModelMapContentType $type = null,
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllEventsEventsGet'][0]
    ): array {
        $request = $this->getAllEventsEventsGetRequest($type, $page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\DataPageEventSchema',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kehet\ArtifactsMMO\Model\DataPageEventSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\DataPageEventSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation getAllEventsEventsGetAsync
     *
     * Get All Events
     *
     * @param  \KehetArtifactsMMOModelMapContentType|null $type Type of events. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllEventsEventsGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getAllEventsEventsGetAsync(
        ?\KehetArtifactsMMOModelMapContentType $type = null,
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllEventsEventsGet'][0]
    ): PromiseInterface {
        return $this->getAllEventsEventsGetAsyncWithHttpInfo($type, $page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllEventsEventsGetAsyncWithHttpInfo
     *
     * Get All Events
     *
     * @param  \KehetArtifactsMMOModelMapContentType|null $type Type of events. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllEventsEventsGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getAllEventsEventsGetAsyncWithHttpInfo(
        ?\KehetArtifactsMMOModelMapContentType $type = null,
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllEventsEventsGet'][0]
    ): PromiseInterface {
        $returnType = '\Kehet\ArtifactsMMO\Model\DataPageEventSchema';
        $request = $this->getAllEventsEventsGetRequest($type, $page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllEventsEventsGet'
     *
     * @param  \KehetArtifactsMMOModelMapContentType|null $type Type of events. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllEventsEventsGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllEventsEventsGetRequest(
        ?\KehetArtifactsMMOModelMapContentType $type = null,
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllEventsEventsGet'][0]
    ): Request {


        if ($page !== null && $page < 1) {
            throw new InvalidArgumentException('invalid value for "$page" when calling EventsApi.getAllEventsEventsGet, must be bigger than or equal to 1.');
        }

        if ($size !== null && $size > 100) {
            throw new InvalidArgumentException('invalid value for "$size" when calling EventsApi.getAllEventsEventsGet, must be smaller than or equal to 100.');
        }
        if ($size !== null && $size < 1) {
            throw new InvalidArgumentException('invalid value for "$size" when calling EventsApi.getAllEventsEventsGet, must be bigger than or equal to 1.');
        }


        $resourcePath = '/events';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type?->value,
            'type', // param base name
            'MapContentType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation spawnEventEventsSpawnPost
     *
     * Spawn Event
     *
     * @param  \Kehet\ArtifactsMMO\Model\SpawnEventRequest $spawn_event_request spawn_event_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['spawnEventEventsSpawnPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Kehet\ArtifactsMMO\Model\ActiveEventResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema
     */
    public function spawnEventEventsSpawnPost(
        \Kehet\ArtifactsMMO\Model\SpawnEventRequest $spawn_event_request,
        string $contentType = self::contentTypes['spawnEventEventsSpawnPost'][0]
    ): \Kehet\ArtifactsMMO\Model\ActiveEventResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema {
        list($response) = $this->spawnEventEventsSpawnPostWithHttpInfo($spawn_event_request, $contentType);
        return $response;
    }

    /**
     * Operation spawnEventEventsSpawnPostWithHttpInfo
     *
     * Spawn Event
     *
     * @param  \Kehet\ArtifactsMMO\Model\SpawnEventRequest $spawn_event_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['spawnEventEventsSpawnPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Kehet\ArtifactsMMO\Model\ActiveEventResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function spawnEventEventsSpawnPostWithHttpInfo(
        \Kehet\ArtifactsMMO\Model\SpawnEventRequest $spawn_event_request,
        string $contentType = self::contentTypes['spawnEventEventsSpawnPost'][0]
    ): array {
        $request = $this->spawnEventEventsSpawnPostRequest($spawn_event_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ActiveEventResponseSchema',
                        $request,
                        $response,
                    );
                case 563:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 564:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 451:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kehet\ArtifactsMMO\Model\ActiveEventResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ActiveEventResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 563:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 564:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 451:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation spawnEventEventsSpawnPostAsync
     *
     * Spawn Event
     *
     * @param  \Kehet\ArtifactsMMO\Model\SpawnEventRequest $spawn_event_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['spawnEventEventsSpawnPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function spawnEventEventsSpawnPostAsync(
        \Kehet\ArtifactsMMO\Model\SpawnEventRequest $spawn_event_request,
        string $contentType = self::contentTypes['spawnEventEventsSpawnPost'][0]
    ): PromiseInterface {
        return $this->spawnEventEventsSpawnPostAsyncWithHttpInfo($spawn_event_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation spawnEventEventsSpawnPostAsyncWithHttpInfo
     *
     * Spawn Event
     *
     * @param  \Kehet\ArtifactsMMO\Model\SpawnEventRequest $spawn_event_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['spawnEventEventsSpawnPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function spawnEventEventsSpawnPostAsyncWithHttpInfo(
        \Kehet\ArtifactsMMO\Model\SpawnEventRequest $spawn_event_request,
        string $contentType = self::contentTypes['spawnEventEventsSpawnPost'][0]
    ): PromiseInterface {
        $returnType = '\Kehet\ArtifactsMMO\Model\ActiveEventResponseSchema';
        $request = $this->spawnEventEventsSpawnPostRequest($spawn_event_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'spawnEventEventsSpawnPost'
     *
     * @param  \Kehet\ArtifactsMMO\Model\SpawnEventRequest $spawn_event_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['spawnEventEventsSpawnPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function spawnEventEventsSpawnPostRequest(
        \Kehet\ArtifactsMMO\Model\SpawnEventRequest $spawn_event_request,
        string $contentType = self::contentTypes['spawnEventEventsSpawnPost'][0]
    ): Request {

        // verify the required parameter 'spawn_event_request' is set
        if ($spawn_event_request === null || (is_array($spawn_event_request) && count($spawn_event_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $spawn_event_request when calling spawnEventEventsSpawnPost'
            );
        }


        $resourcePath = '/events/spawn';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($spawn_event_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($spawn_event_request));
            } else {
                $httpBody = $spawn_event_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
