<?php

/**
 * MonstersApi
 * PHP version 8.1
 *
 * @package  Kehet\ArtifactsMMO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kehet\ArtifactsMMO\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Kehet\ArtifactsMMO\ApiException;
use Kehet\ArtifactsMMO\Configuration;
use Kehet\ArtifactsMMO\HeaderSelector;
use Kehet\ArtifactsMMO\FormDataProcessor;
use Kehet\ArtifactsMMO\ObjectSerializer;

/**
 * MonstersApi Class Doc Comment
 *
 * @package  Kehet\ArtifactsMMO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MonstersApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAllMonstersMonstersGet' => [
            'application/json',
        ],
        'getMonsterMonstersCodeGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation getAllMonstersMonstersGet
     *
     * Get All Monsters
     *
     * @param  string|null $name Name of the monster. (optional)
     * @param  int|null $min_level Minimum level. (optional)
     * @param  int|null $max_level Maximum level. (optional)
     * @param  string|null $drop Item code of the drop. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllMonstersMonstersGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Kehet\ArtifactsMMO\Model\DataPageMonsterSchema
     */
    public function getAllMonstersMonstersGet(
        ?string $name = null,
        ?int $min_level = null,
        ?int $max_level = null,
        ?string $drop = null,
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllMonstersMonstersGet'][0]
    ): \Kehet\ArtifactsMMO\Model\DataPageMonsterSchema {
        list($response) = $this->getAllMonstersMonstersGetWithHttpInfo($name, $min_level, $max_level, $drop, $page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getAllMonstersMonstersGetWithHttpInfo
     *
     * Get All Monsters
     *
     * @param  string|null $name Name of the monster. (optional)
     * @param  int|null $min_level Minimum level. (optional)
     * @param  int|null $max_level Maximum level. (optional)
     * @param  string|null $drop Item code of the drop. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllMonstersMonstersGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Kehet\ArtifactsMMO\Model\DataPageMonsterSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllMonstersMonstersGetWithHttpInfo(
        ?string $name = null,
        ?int $min_level = null,
        ?int $max_level = null,
        ?string $drop = null,
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllMonstersMonstersGet'][0]
    ): array {
        $request = $this->getAllMonstersMonstersGetRequest($name, $min_level, $max_level, $drop, $page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\DataPageMonsterSchema',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kehet\ArtifactsMMO\Model\DataPageMonsterSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\DataPageMonsterSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation getAllMonstersMonstersGetAsync
     *
     * Get All Monsters
     *
     * @param  string|null $name Name of the monster. (optional)
     * @param  int|null $min_level Minimum level. (optional)
     * @param  int|null $max_level Maximum level. (optional)
     * @param  string|null $drop Item code of the drop. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllMonstersMonstersGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getAllMonstersMonstersGetAsync(
        ?string $name = null,
        ?int $min_level = null,
        ?int $max_level = null,
        ?string $drop = null,
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllMonstersMonstersGet'][0]
    ): PromiseInterface {
        return $this->getAllMonstersMonstersGetAsyncWithHttpInfo($name, $min_level, $max_level, $drop, $page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllMonstersMonstersGetAsyncWithHttpInfo
     *
     * Get All Monsters
     *
     * @param  string|null $name Name of the monster. (optional)
     * @param  int|null $min_level Minimum level. (optional)
     * @param  int|null $max_level Maximum level. (optional)
     * @param  string|null $drop Item code of the drop. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllMonstersMonstersGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getAllMonstersMonstersGetAsyncWithHttpInfo(
        ?string $name = null,
        ?int $min_level = null,
        ?int $max_level = null,
        ?string $drop = null,
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllMonstersMonstersGet'][0]
    ): PromiseInterface {
        $returnType = '\Kehet\ArtifactsMMO\Model\DataPageMonsterSchema';
        $request = $this->getAllMonstersMonstersGetRequest($name, $min_level, $max_level, $drop, $page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllMonstersMonstersGet'
     *
     * @param  string|null $name Name of the monster. (optional)
     * @param  int|null $min_level Minimum level. (optional)
     * @param  int|null $max_level Maximum level. (optional)
     * @param  string|null $drop Item code of the drop. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllMonstersMonstersGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllMonstersMonstersGetRequest(
        ?string $name = null,
        ?int $min_level = null,
        ?int $max_level = null,
        ?string $drop = null,
        ?int $page = 1,
        ?int $size = 50,
        string $contentType = self::contentTypes['getAllMonstersMonstersGet'][0]
    ): Request {

        if ($name !== null && !preg_match("/^[a-zA-Z0-9_-]+(\\s[a-zA-Z0-9_-]+)*\\s?$/", $name)) {
            throw new InvalidArgumentException("invalid value for \"name\" when calling MonstersApi.getAllMonstersMonstersGet, must conform to the pattern /^[a-zA-Z0-9_-]+(\\s[a-zA-Z0-9_-]+)*\\s?$/.");
        }

        if ($min_level !== null && $min_level < 0) {
            throw new InvalidArgumentException('invalid value for "$min_level" when calling MonstersApi.getAllMonstersMonstersGet, must be bigger than or equal to 0.');
        }

        if ($max_level !== null && $max_level < 0) {
            throw new InvalidArgumentException('invalid value for "$max_level" when calling MonstersApi.getAllMonstersMonstersGet, must be bigger than or equal to 0.');
        }

        if ($drop !== null && !preg_match("/^[a-zA-Z0-9_-]+$/", $drop)) {
            throw new InvalidArgumentException("invalid value for \"drop\" when calling MonstersApi.getAllMonstersMonstersGet, must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }

        if ($page !== null && $page < 1) {
            throw new InvalidArgumentException('invalid value for "$page" when calling MonstersApi.getAllMonstersMonstersGet, must be bigger than or equal to 1.');
        }

        if ($size !== null && $size > 100) {
            throw new InvalidArgumentException('invalid value for "$size" when calling MonstersApi.getAllMonstersMonstersGet, must be smaller than or equal to 100.');
        }
        if ($size !== null && $size < 1) {
            throw new InvalidArgumentException('invalid value for "$size" when calling MonstersApi.getAllMonstersMonstersGet, must be bigger than or equal to 1.');
        }


        $resourcePath = '/monsters';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name,
            'name', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $min_level,
            'min_level', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_level,
            'max_level', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $drop,
            'drop', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMonsterMonstersCodeGet
     *
     * Get Monster
     *
     * @param  string $code The code of the monster. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMonsterMonstersCodeGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Kehet\ArtifactsMMO\Model\MonsterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema
     */
    public function getMonsterMonstersCodeGet(
        string $code,
        string $contentType = self::contentTypes['getMonsterMonstersCodeGet'][0]
    ): \Kehet\ArtifactsMMO\Model\MonsterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema {
        list($response) = $this->getMonsterMonstersCodeGetWithHttpInfo($code, $contentType);
        return $response;
    }

    /**
     * Operation getMonsterMonstersCodeGetWithHttpInfo
     *
     * Get Monster
     *
     * @param  string $code The code of the monster. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMonsterMonstersCodeGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \Kehet\ArtifactsMMO\Model\MonsterResponseSchema|\Kehet\ArtifactsMMO\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMonsterMonstersCodeGetWithHttpInfo(
        string $code,
        string $contentType = self::contentTypes['getMonsterMonstersCodeGet'][0]
    ): array {
        $request = $this->getMonsterMonstersCodeGetRequest($code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\MonsterResponseSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }


            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kehet\ArtifactsMMO\Model\MonsterResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\MonsterResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kehet\ArtifactsMMO\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation getMonsterMonstersCodeGetAsync
     *
     * Get Monster
     *
     * @param  string $code The code of the monster. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMonsterMonstersCodeGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getMonsterMonstersCodeGetAsync(
        string $code,
        string $contentType = self::contentTypes['getMonsterMonstersCodeGet'][0]
    ): PromiseInterface {
        return $this->getMonsterMonstersCodeGetAsyncWithHttpInfo($code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMonsterMonstersCodeGetAsyncWithHttpInfo
     *
     * Get Monster
     *
     * @param  string $code The code of the monster. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMonsterMonstersCodeGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getMonsterMonstersCodeGetAsyncWithHttpInfo(
        string $code,
        string $contentType = self::contentTypes['getMonsterMonstersCodeGet'][0]
    ): PromiseInterface {
        $returnType = '\Kehet\ArtifactsMMO\Model\MonsterResponseSchema';
        $request = $this->getMonsterMonstersCodeGetRequest($code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMonsterMonstersCodeGet'
     *
     * @param  string $code The code of the monster. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMonsterMonstersCodeGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMonsterMonstersCodeGetRequest(
        string $code,
        string $contentType = self::contentTypes['getMonsterMonstersCodeGet'][0]
    ): Request {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $code when calling getMonsterMonstersCodeGet'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_-]+$/", $code)) {
            throw new InvalidArgumentException("invalid value for \"code\" when calling MonstersApi.getMonsterMonstersCodeGet, must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }


        $resourcePath = '/monsters/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'], true)) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
