<?php
/**
 * CharacterLeaderboardSchemaTest
 *
 * PHP version 8.1
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace \Kehet\ArtifactsMMO\\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CharacterLeaderboardSchemaTest Class Doc Comment
 *
 * @description CharacterLeaderboardSchema
 * @package     \Kehet\ArtifactsMMO\
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CharacterLeaderboardSchemaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CharacterLeaderboardSchema"
     */
    public function testCharacterLeaderboardSchema()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "skin"
     */
    public function testPropertySkin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_xp"
     */
    public function testPropertyTotalXp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mining_level"
     */
    public function testPropertyMiningLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mining_total_xp"
     */
    public function testPropertyMiningTotalXp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "woodcutting_level"
     */
    public function testPropertyWoodcuttingLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "woodcutting_total_xp"
     */
    public function testPropertyWoodcuttingTotalXp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fishing_level"
     */
    public function testPropertyFishingLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fishing_total_xp"
     */
    public function testPropertyFishingTotalXp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "weaponcrafting_level"
     */
    public function testPropertyWeaponcraftingLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "weaponcrafting_total_xp"
     */
    public function testPropertyWeaponcraftingTotalXp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gearcrafting_level"
     */
    public function testPropertyGearcraftingLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gearcrafting_total_xp"
     */
    public function testPropertyGearcraftingTotalXp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "jewelrycrafting_level"
     */
    public function testPropertyJewelrycraftingLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "jewelrycrafting_total_xp"
     */
    public function testPropertyJewelrycraftingTotalXp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cooking_level"
     */
    public function testPropertyCookingLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cooking_total_xp"
     */
    public function testPropertyCookingTotalXp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alchemy_level"
     */
    public function testPropertyAlchemyLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alchemy_total_xp"
     */
    public function testPropertyAlchemyTotalXp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gold"
     */
    public function testPropertyGold()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
