<?php
/**
 * FakeCharacterSchemaTest
 *
 * PHP version 8.1
 *
 * @package  \Kehet\ArtifactsMMO\
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 6.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace \Kehet\ArtifactsMMO\\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FakeCharacterSchemaTest Class Doc Comment
 *
 * @description FakeCharacterSchema
 * @package     \Kehet\ArtifactsMMO\
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FakeCharacterSchemaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FakeCharacterSchema"
     */
    public function testFakeCharacterSchema()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "weapon_slot"
     */
    public function testPropertyWeaponSlot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rune_slot"
     */
    public function testPropertyRuneSlot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shield_slot"
     */
    public function testPropertyShieldSlot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "helmet_slot"
     */
    public function testPropertyHelmetSlot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "body_armor_slot"
     */
    public function testPropertyBodyArmorSlot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "leg_armor_slot"
     */
    public function testPropertyLegArmorSlot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "boots_slot"
     */
    public function testPropertyBootsSlot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ring1_slot"
     */
    public function testPropertyRing1Slot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ring2_slot"
     */
    public function testPropertyRing2Slot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amulet_slot"
     */
    public function testPropertyAmuletSlot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "artifact1_slot"
     */
    public function testPropertyArtifact1Slot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "artifact2_slot"
     */
    public function testPropertyArtifact2Slot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "artifact3_slot"
     */
    public function testPropertyArtifact3Slot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "utility1_slot"
     */
    public function testPropertyUtility1Slot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "utility1_slot_quantity"
     */
    public function testPropertyUtility1SlotQuantity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "utility2_slot"
     */
    public function testPropertyUtility2Slot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "utility2_slot_quantity"
     */
    public function testPropertyUtility2SlotQuantity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
